---
sidebar: sidebar 
permalink: aqos-kfs.html 
keywords: aqos, qos, adaptive quality of service, quality of service 
summary: 'Keystone 적응형 서비스 품질(AQoS)' 
---
= Keystone의 적응형 서비스 품질
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
스토리지 서비스 품질(QoS)은 애플리케이션이 예측 가능하고 일관된 성능을 확보할 수 있도록 보장하는 중요한 기술입니다. QoS를 사용하지 않을 경우, 여러 시스템의 부팅에 대한 워크로드 같은 특정 워크로드는 일정 기간 동안 대부분의 리소스 또는 모든 리소스를 소모하며 다른 워크로드에 영향을 미칠 수 있습니다. QoS에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["QoS 개요를 통해 처리량 보장"^].



== 적응형 QoS

Keystone 서비스에서 AQoS(적응형 QoS)를 사용하여 볼륨 크기에 따라 IOPS/TiB 비율을 동적으로 유지합니다. AQoS 정책에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["적응형 QoS에 대해 알아보십시오"^].

Keystone은 클러스터가 운영 중인 경우 설정할 수 있는 AQoS 정책을 제공합니다. 모든 볼륨이 시스템에서 이미 생성되어 사용 가능한 올바른 AQoS 정책과 연결되어 있는지 확인해야 합니다.

ONTAP 볼륨에 AQoS 정책이 적용되지 않은 경우 해당 볼륨은 규정을 준수하지 않습니다. QoS 정책이 없는 볼륨은 시스템에서 사용 가능한 입력/출력 작업을 제공하는 데 필요한 우선 순위 목록의 마지막 볼륨입니다. 그러나 입력-출력 작업을 사용할 수 있는 경우 볼륨은 사용 가능한 모든 IO를 소모할 수 있습니다.


NOTE: 볼륨에 AQoS 정책을 적용하지 않은 경우, 해당 볼륨은 가입자 서비스에 따라 가장 높은 서비스 수준에서 측정 및 청구됩니다. 이로 인해 의도하지 않은 폭발이 발생할 수 있습니다.



=== 적응형 QoS 설정

AQoS(Adaptive QoS) 설정은 서비스 수준에 따라 다릅니다.

|===


| * 정책 이름 * | * Extreme * 및 * Extreme Tiering * | * 프리미엄 * 및 * 프리미엄 계층화 * | * 표준 * | * 값 * 


| * 예상 IOPS * | 6,144 | 2,048 | 128 | 64 


| * 예상 IOPS 할당 * 4+| 할당된 공간입니다 


| * 최대 IOPS * | 12,288 | 4,096개 | 512 | 128 


| * 최대 IOPS 할당 * 4+| 할당된 공간입니다 


| * 블록 크기 * 4+| 32K 
|===