---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, 
summary: 유연한 Keystone 구독 성능 
---
= 서비스 레벨
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 유연한 구독(유연한 구독)은 사전 정의된 서비스 수준 또는 성능 서비스 수준에서 용량을 제공합니다.

각 서비스 수준(서비스 수준)은 I/O 밀도로 정의됩니다. 이 밀도는 IOPS/TiB에 해당하는 성능(초당 입출력 작업 수[IOPS]) 및 사용된 스토리지(저장된 데이터의 TiB)의 비율입니다.

Flex Subscription 서비스에서 관리하는 각 볼륨은 서비스 수준과 연결됩니다. 각 볼륨에서 사용된 모든 I/O 작업과 사용된 모든 스토리지는 볼륨의 I/O 밀도 계산에 포함됩니다.

아래 표에는 서비스 수준이 정의되어 있습니다.



== 스토리지 유형 차이에 대한 서비스 수준

여기에 파일, 블록 및 오브젝트 스토리지의 서비스 수준이 나와 있습니다.

볼륨 레벨의 I/O 밀도 계산은 이전 주 동안의 최대 I/O 밀도를 보여 주는 것으로 보고됩니다. 최대 성능은 시간별 시간 간격에 따라 결정됩니다. 볼륨별 I/O 밀도 보고서는 각 서비스 수준에 대한 준수 여부를 측정하기 위해 매월 생성됩니다.



=== 파일 서비스

* 지원되는 프로토콜 *: NFS, CIFS, iSCSI, FC

|===


| * 서비스 수준 * | * 익스트림 * | * 프리미엄 * | * 표준 * | * 값 * 


| * 워크로드 유형 * | 분석, 데이터베이스 | VDI, 가상화 애플리케이션, 소프트웨어 개발 | 파일 공유, 웹 서버 | 백업 


| * 타겟 IOPS/TiB * | 6,144 | 2,048 | 128 | 해당 없음 


| * 최대 IOPS/TiB * | 12,288 | 4,096개 | 512 | 해당 없음 


| * 최대 처리량 MBps(32KB/IOP) * | 384 | 128 | 16 | 해당 없음 


| * 지연 시간 * | 1ms 미만 | 2ms 미만 | 17ms 미만 | 해당 없음 


.2+| * 최소 용량 *^1,2^ 4+| 100TiB^1^ 


| 15TiB^2^ | 25TiB^2^ | 50TiB^2^ | 50TiB^2^ 
|===

NOTE: ^1^NetApp 직접 기회에 대한 파일 공유와 블록 서비스 수준을 결합할 경우 최소 1년 및 100TiB 최소 용량을 제공합니다. ^2^채널 주도 기회를 위해 선택한 각 서비스 계층당 최소 1년 간의 기간 및 최소 명시된 용량입니다.



=== 블록 스토리지

* 지원되는 프로토콜 *: FC 및 iSCSI

|===


| * 서비스 수준 * | * 익스트림 * | * 프리미엄 * | * 표준 * 


| * 워크로드 유형 * | HPC | 비디오 감시 | 백업 


| * 타겟 IOPS/TiB * 3+| 해당 없음 


| * 최대 IOPS/TiB * | 5.500 | 4,000 | 해당 없음 


| * 최대 처리량 MBps(32KB/IOP) * | 43 | 31 | 해당 없음 


| * 지연 시간 * | 0.5ms 미만 | 0.5ms 미만 | 해당 없음 


| * 최소 용량 *^1,2^ | 100TiB^3^ | 100TiB^3^ | 300TiB^3^ 
|===

NOTE: ^1^NetApp 직접 기회에 대한 파일 공유와 블록 서비스 수준을 결합할 경우 최소 1년 및 100TiB 최소 용량을 제공합니다. ^2^채널 주도 기회를 위해 선택한 서비스 계층당 최소 1년 기간 및 최소 명시된 용량. ^3^ 두 기회 유형 중 하나에 대해 선택한 서비스 계층당 최소 1년 기간 및 최소 명시된 용량.



=== 오브젝트 스토리지

* 지원되는 프로토콜 *: S3

|===


| * 서비스 수준 * | 오브젝트 


| * 워크로드 유형 * | 미디어 저장소, 아카이브 


| * 타겟 IOPS/TiB * | 해당 없음 


| * 최대 IOPS/TiB * | 해당 없음 


| * 최대 처리량 MBps(32KB/IOP) * | 해당 없음 


| * 지연 시간 * | 해당 없음 


| * 최소 용량 *^1,2^ | 500TiB^3^ 
|===

NOTE: ^1^NetApp 직접 기회에 대한 파일 공유와 블록 서비스 수준을 결합할 경우 최소 1년 및 100TiB 최소 용량을 제공합니다. ^2^채널 주도 기회를 위해 선택한 서비스 계층당 최소 1년 기간 및 최소 명시된 용량. ^3^ 두 기회 유형 중 하나에 대해 선택한 서비스 계층당 최소 1년 기간 및 최소 명시된 용량.

NetApp Service Engine 사용자 인터페이스의 여러 화면에서 구독에 서비스 수준을 할당할 수 있습니다. 자세한 내용은 다음을 참조하십시오.

* * * link:nkfsosm_tenancy_overview.html["유연한 서브스크립션의 테넌시 및 멀티 테넌시"]
