---
sidebar: sidebar 
permalink: nkfsfaq_netapp_service_engine_self-service_access_portal.html 
keywords: netapp, keystone, service, engine, self-service, acess, portal, 
summary: NetApp 서비스 엔진/셀프 서비스 액세스 포털 
---
= NetApp Service Engine/셀프 서비스 액세스 포털
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 FAQ는 NetApp 서비스 엔진에 적용됩니다.



=== NetApp 서비스 엔진이란 무엇입니까?

NetApp 서비스 엔진은 NetApp에서 운영하는 모델에서 셀프 서비스 포털로 NetApp Keystone 유연한 구독 서비스에 기반하여 스토리지 로그인 및 프로비저닝할 수 있습니다. 또한 이 툴은 구독의 소비 수준에 대한 보고서를 제공하고 모든 서비스 요청 또는 구독 변경을 시작합니다.



=== 고객 운영 모델에 NetApp 서비스 엔진이 필요합니까?

고객이 운영하는 모델에는 NetApp 서비스 엔진이 필요합니다. 이 보고서는 소비 상세 정보에 대한 기본 보고서를 제공하며 청구 정보를 수집하고 보고하는 데 필요합니다.



=== NetApp 서비스 엔진은 어디에 설치됩니까?

NetApp 운영 모델에서 NetApp 서비스 엔진은 NetApp에서 제공하는 컴퓨팅 리소스에 로컬로 설치됩니다. 고객 운영 모델에서 NetApp 서비스 엔진은 고객이 제공한 컴퓨팅 리소스에 설치됩니다.



=== NetApp 서비스 엔진에 로그인할 수 있는 사람은 누구입니까?

NetApp 서비스 엔진에 구성된 NetApp SSO 또는 로컬 사용자에 대해 사용자를 인증할 수 있습니다.



=== 액세스는 어떻게 제어됩니까?

NetApp 서비스 엔진은 역할 기반 액세스 제어(RBAC) 기능을 제공하며, 각 사용자는 역할에 연결할 수 있으므로 사용자가 수행할 수 있는 작업을 정의합니다. RBAC 할당은 NetApp 서비스 엔진을 사용하여 고객이 수행합니다.



=== 어떤 액세스 컨트롤을 사용할 수 있습니까?

다음과 같은 액세스 컨트롤을 사용할 수 있습니다.

* * 파트너 관리자 * 테넌트를 생성 및 관리하고, 테넌트에 대한 가입을 관리하고, 사용 보고서를 보고, 스토리지의 기술적 측면을 관리할 수 있는 권한을 가진 파트너 측의 관리자.
* * 고객/테넌트 관리자 * 가입 변경 요청, 새 사용자 및 하위 테넌트 생성, 파일 공유, 디스크 및 버킷을 생성 및 볼 수 있는 권한을 가진 고객 측 관리자.
* * NetApp 관리자(읽기). * 웹 포털의 모든 구성 요소에 액세스할 수 있고 모든 NetApp Keystone 유연한 구독, 파트너 및 테넌트 구독, 스토리지 등의 모든 세부 정보를 볼 수 있는 NetApp 관리자. 그러나 이 사용자는 생성, 편집 또는 삭제할 권한이 없습니다.
* * NetApp Admin. * 이 사용자는 NetApp 서비스 엔진 웹 포털에서 모든 기능을 수행할 수 있는 모든 권한과 권한을 가지고 있어 NetApp Keystone 유연한 구독 관리와 파트너 및 테넌트 관리를 위한 모든 활동을 관리할 수 있습니다.




=== 사용량에 대한 청구서는 어디에서 확인할 수 있습니까?

대시보드의 * Monthly 요금 * 위젯에서 지난 3개월 동안의 구독에 대한 집계된 월별 요금을 볼 수 있습니다. 위젯을 클릭하거나 * 관리 * > * 청구 * 로 이동하여 자세한 청구 정보를 볼 수 있습니다.
