---
sidebar: sidebar 
permalink: nkfsosm_tiering.html 
keywords: netapp, keystone, tiering, 
summary: Keystone 계층화 
---
= 계층화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 유연한 구독 서비스에는 자주 사용하지 않는 데이터를 식별하고 NetApp이 소유, 구축, 관리하는 콜드 스토리지에 계층화하는 계층화 기능이 포함됩니다.

계층화 기능은 NetApp FabricPool 기술을 활용하여 사내 또는 사외에서 데이터를 저비용 오브젝트 스토리지 계층으로 자동 계층화할 수 있습니다. 이 기능을 사용하면 자주 액세스하지 않는 데이터는 합의된 서비스에 따라 사내 또는 클라우드의 저렴한 스토리지로 자동으로 계층됩니다.

파트너와 테넌트는 사전 구성된 두 가지 서비스 수준, 즉 스토리지의 용량을 할당하는 동시에 Extreme-Tiering 및 Premium-Tiering 서비스 수준을 선택함으로써 이 기능을 쉽게 사용할 수 있습니다. 익스트림 계층화는 표준, 익스트림 및 프리미엄 서비스 수준과 동일한 QoS 정책을 갖습니다.

애드온 계층화 기능은 Extreme 및 Premium 서비스 계층에서만 사용할 수 있습니다. NetApp은 25%의 데이터가 핫 데이터이고 75%의 빈도가 낮은 것으로 가정하며 콜드 스토리지로 이동할 수 있습니다. 각 서비스 수준에서 볼륨당 기간에 따라 청구가 결정됩니다.

다음 기능이 활성화됩니다.

* 디스크 및 파일 공유에 대한 비활성 데이터 보고서를 생성하고 서비스 레벨 변경 여부를 결정할 수 있습니다. 계층화 정책을 이동하거나 변경할 때, 콜드 계층에서 데이터에 액세스할 경우 지연 시간이 길어질 수 있습니다.
* 클러스터에서 대상 계층화가 활성화된 경우 볼륨의 서비스 수준을 Extreme 및 Premium에서 Extreme-Tiering 및 Premium 계층화로 각각 변경할 수 있습니다.
* 마찬가지로, 계층화 서비스 수준을 볼륨에 대한 비계층화로 변경할 수 있습니다.
* 계층화 서비스 수준에서 볼륨에 대한 백업을 설정 및 해제합니다.
* 계층화 서비스 수준에서 볼륨에 대한 재해 복구를 설정 및 해제합니다.

