---
sidebar: sidebar 
permalink: nkfsfaq_overview.html 
keywords: netapp, keystone, overview, 
summary: NetApp Keystone 개요 
---
= NetApp Keystone FAQ(자주 묻는 질문)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 질문을 통해 NetApp Keystone에 대한 자주 묻는 질문에 대한 답변을 얻을 수 있습니다.

* NetApp Keystone란? *

NetApp Keystone는 온프레미스 자본 지출(CapEx) 대체 포트폴리오입니다.
자세한 내용은 을 참조하십시오 https://www.netapp.com/services/keystone/["NetApp Keystone"^].

* NetApp Keystone은 고객에게 어떤 이점을 제공합니까? *

NetApp Keystone은 CapEx 및 하이브리드 클라우드 전략의 주요 요소인 민첩성, 재무 유연성, 재무 위험 감소를 서로 연계하고 고객이 현금 유동성 및 비즈니스 요구사항을 충족하도록 지원합니다.

NetApp Keystone 브랜드는 Keystone 서비스와 함께 현금을 중요시하는 고객을 위한 기존 금융, 리스 및 고정/가변 옵션을 포함하는 유연한 지불 솔루션 포트폴리오를 제공합니다.

* Keystone 서비스(OpEx, 클라우드형 경험): *
* 100% OpEx를 선호하므로 자산이 고객의 대차대조표에 포함되지 않습니다
* 사용량/수익에 맞춰 비용을 조정하고자 하는 내부/외부 서비스 공급자
* 예측할 수 없는 용량 증가로 인한 워크로드
* 일반적인 스토리지 작업(마이그레이션, 기술 업데이트, 업그레이드 등)에서 재할당된 IT 리소스
* 워크로드를 클라우드로 마이그레이션하기 전의 단기적인 솔루션입니다
* 클라우드에서 온프레미스로 워크로드를 다시 이동합니다

* NetApp Keystone란? *

NetApp Keystone는 새롭고 유연한 온프레미스 구독 기반 조달 모델입니다. 고객은 리소스 관리의 장애물을 제거하고 긴 조달 주기를 거치는 등, 가치 창출 시간을 앞당길 수 있습니다. Keystone 서비스를 통해 고객은 비즈니스 우선순위에 맞게 경제성을 조정할 수 있습니다. 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription["여기"].

* 온프레미스의 의미는 무엇입니까? *

사내는 코로케이션 시설에서 고객 소유 데이터 센터 또는 고객 소유 공간으로 정의됩니다. 고객은 공간, 전력 및 냉각에 대한 책임이 있습니다.

* Keystone 서비스의 이점은 무엇입니까? *

Keystone 서비스의 몇 가지 이점은 다음과 같습니다.

* IT 직원의 업무 부담을 복잡한 스토리지 관련 작업에서 해방시키고 애플리케이션 관리에 집중할 수 있도록 함
* 초기 자본 투자 감소
* 오버 프로비저닝 없이 고객의 요구사항을 충족할 수 있습니다
* 데이터 스토리지 비용을 비즈니스 요구사항/활동에 맞게 조정
* 복잡한 조직의 조달 절차를 거치지 않고 인프라 프로비저닝을 간소화합니다
* 사내 데이터의 보안 유지
* 규정 준수, 성능 및 보안에 대한 적절한 제어 가능 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription["여기"].

