---
sidebar: sidebar 
permalink: nkfsosm-keystone-and-aiq.html 
keywords: netapp, keystone, aiq keystone customers, Active IQ and keystone 
summary: 고객이 Active IQ Keystone에 대해 확인할 수 있는 내용 
---
= Active IQ에서 Flex Subscription 고객은 무엇을 볼 수 있습니까?
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 유연한 구독(유연한 구독) 서비스에 가입한 경우 Active IQ 디지털 자문 대시보드에서 사용 보고서 및 그래프를 볼 수 있습니다.

Active IQ 디지털 어드바이저에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/us-en/active-iq/index.html["Active IQ 디지털 자문 문서"]

사이트에 NetApp 서비스 엔진이 기본적으로 설치되어 있으면 Active IQ 디지털 조언자 외에도 NetApp 서비스 엔진 인터페이스를 통해 소비 차트를 확인할 수 있습니다. 그러나 고객이 관리하는 환경에서는 NetApp 서비스 엔진 인터페이스에 액세스할 수 없으며 용량 차트 및 사용 현황 보고서는 Active IQ Digital Advisor 대시보드를 통해서만 볼 수 있습니다. 고객이 관리하는 환경에 대한 자세한 내용은 를 참조하십시오 link:nkfsosm_overview.html["운영 모델, 역할 및 책임"]

사이트에서 메트릭 데이터 수집 간격은 5분입니다.

고객은 유연한 구독 서비스에 가입한 경우 Active IQ 디지털 어드바이저에서 다음 정보를 볼 수 있습니다.

* * Keystone 유연한 구독 * 위젯: Active IQ 디지털 어드바이저에 로그인한 경우 구매한 유연한 구독 서비스에 대한 용량 사용을 요약하는 * Keystone 유연한 구독 * 위젯을 확인할 수 있습니다.
* 위젯에서 * 세부 정보 보기 * 를 클릭하면 * Keystone-용량 활용률 * 대시보드를 볼 수 있습니다. Keystone - 용량 활용률 * 대시보드는 서비스 수준, 데이터 보호, 고급 데이터 보호 서비스 등 가입된 서비스에 따라 용량 및 사용 데이터에 대한 추가 분석 및 분석 기능을 제공합니다. 또한 대시보드에는 최근 1, 7, 30일 동안의 소비된 용량, 약정 용량 및 버스트 용량 사용량 그래프가 표시됩니다. 평균 누적 비율은 현재 청구 기간 동안 계산 및 분할됩니다.


자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/active-iq/task_view_keystone_capacity_utilization.html["NetApp Keystone 유연한 구독으로 용량 활용도를 확인할 수 있습니다"].
