---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, service levels 
summary: Keystone 퍼포먼스 서비스 수준 
---
= 서비스 레벨
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone은 미리 정의된 성능 서비스 수준(서비스 수준)에 데이터 스토리지 용량을 제공하거나 구독 기준으로 계획 등급을 매기십시오. Keystone 서비스로 관리되는 각 볼륨은 서비스 수준과 연결되어 있습니다.

각 서비스 수준은 I/O 밀도, 즉 IOPS/TiB/볼륨으로 정의됩니다. 볼륨당 평균 지연 시간에서 IOPS/TiB인 성능(IOPS/출력 작업/IOPS) 및 할당 스토리지 용량(TiB)의 비율입니다.

볼륨의 I/O 밀도는 피크 I/O 밀도를 보고하기 위해 시간 간격으로 계산됩니다. 볼륨에 대한 I/O 밀도 보고서는 매월 생성됩니다.

스토리지 환경, 스토리지 및 소비 요구사항에 따라 서비스 수준을 선택합니다. 기본적으로 기본 서비스 수준을 사용할 수 있습니다. 특정 서비스를 선택한 경우 기타 서비스 수준을 추가로 이용할 수 있습니다. 예를 들어, 데이터 보호 서비스의 경우 _data-protect <base-service-level>_service 수준이 구독에 할당됩니다.

여기에 파일, 블록 및 오브젝트 스토리지 유형에 대한 기본 서비스 수준이 나와 있습니다.



== 파일 스토리지의 서비스 레벨

* 지원되는 프로토콜 *: NFS, CIFS, iSCSI, FC

|===


| * 서비스 수준 * | * 익스트림 * | * 프리미엄 * | * 표준 * | * 값 * 


| * 워크로드 유형 * | 분석, 데이터베이스 | VDI, 가상화 애플리케이션, 소프트웨어 개발 | 파일 공유, 웹 서버 | 백업 


| * 볼륨당 할당된 최대 IOPS/논리적 TiB * | 12,288 | 4,096개 | 512 | 해당 없음 


| * 볼륨당 할당된 타겟 IOPS/논리적 TiB * | 6,144 | 2,048 | 128 | 해당 없음 


| * 볼륨당 할당된 최대 MBps/논리적 TiB * | 384 | 128 | 16 | 해당 없음 


| * 평균 지연 시간 * | 1ms 미만 | 2ms 미만 | 17ms 미만 | 해당 없음 


| * 블록 크기 * 4+| 32K 
|===


=== 파일 스토리지의 서비스 수준 자세히 보기

기본 서비스 수준 메트릭은 다음 조건에 따라 달라집니다.

* 파일 및 블록 스토리지의 서비스 수준은 ONTAP 9.7 이상을 지원합니다.
* 서비스 수준의 IOPS/TiB/볼륨, MBps/TiB/볼륨 및 지연 시간은 볼륨에 저장된 논리적 데이터의 양, 32KB 블록 크기, 70% 읽기 및 30% 쓰기 IO 작업의 임의 조합을 기준으로 합니다.
* 실제 IOPS/TiB/볼륨 및 MBps/TiB/볼륨은 실제 또는 가정된 블록 크기, 시스템 워크로드 동시성 또는 입력 출력 작업에 따라 달라질 수 있습니다.
* 지연 시간은 다음 사항을 포함하지 않습니다.
+
** 애플리케이션 또는 호스트 지연 시간
** 컨트롤러 포트 간 또는 컨트롤러 포트로 전송되는 고객의 네트워크 지연 시간
** FabricPool의 경우 데이터 전송과 관련된 오버헤드를 오브젝트 저장소로 이동합니다
** 지연 시간은 서비스 수준 최대 내에서 입출력을 유지하기 위해 QoS에 의해 자동으로 적용됩니다


* 지연 시간 값은 MetroCluster 쓰기 작업에 적용할 수 없습니다. 이러한 쓰기 작업은 원격 시스템의 거리에 따라 달라집니다.
* 스토리지 시스템의 볼륨 중 하나 이상에 AQoS 정책이 할당되어 있지 않은 경우 이러한 볼륨은 비준수 볼륨으로 간주되며 이러한 시스템에 적용되는 타겟 서비스 수준이 없습니다.
* _expected IOPS_는 계층화 정책이 "없음"으로 설정되고 클라우드에 블록이 없는 경우에만 FabricPool를 대상으로 합니다. _expected IOPS_는 SnapMirror 동기식 관계가 아닌 볼륨을 대상으로 합니다.
* 워크로드 IO 작업은 Keystone 순서에 따라 구축된 모든 컨트롤러 간에 균형을 이루어야 합니다.




== 블록 스토리지의 서비스 레벨

* 지원되는 프로토콜 *: FC 및 iSCSI

|===


| * 서비스 수준 * | * 익스트림 * | * 프리미엄 * | * 표준 * 


| * 워크로드 유형 * | HPC | 비디오 감시 | 백업 


| * 타겟 IOPS/TiB * 3+| 해당 없음 


| * 최대 IOPS/TiB * | 5,500 | 4,000 | 해당 없음 


| * 최대 처리량 MBps(32KB/IOP) * | 43 | 31 | 해당 없음 


| * 평균 지연 시간 * | 0.5ms 미만 | 0.5ms 미만 | 해당 없음 


| * 블록 크기 * 3+| 32K 
|===


== 오브젝트 스토리지의 서비스 수준

* 지원되는 프로토콜 *: S3

|===


| * 서비스 수준 * | 오브젝트 


| * 워크로드 유형 * | 미디어 저장소, 아카이브 


| * 타겟 IOPS/TiB * | 해당 없음 


| * 최대 IOPS/TiB * | 해당 없음 


| * 최대 처리량 MBps(32KB/IOP) * | 해당 없음 


| * 평균 지연 시간 * | 해당 없음 
|===