---
sidebar: sidebar 
permalink: nkfsfaq_keystone_subscription.html 
keywords: netapp, keystone, subscription, subscriptions, 
summary: NetApp Keystone 구독 
---
= NetApp Keystone 유연한 구독 FAQ
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 질문을 통해 NetApp Keystone 유연한 구독 서비스에 대한 자주 묻는 질문에 대한 답변을 얻을 수 있습니다.



=== NetApp Keystone 유연한 서브스크립션의 일부로 제공되는 것은 무엇입니까?

NetApp Keystone 유연한 구독(Flex Subscription)은 블록, 파일 및 오브젝트 데이터 서비스를 위한 구독 기반 서비스로, 사내에 구축할 수 있으며 NetApp, 파트너 또는 고객이 직접 운영할 수 있습니다.



=== Flex Subscription의 일부로 제공되는 스토리지 서비스는 무엇입니까?

자세한 내용은 을 참조하십시오 link:nkfsosm_performance.html["성능 서비스 레벨"]



=== 어떤 추가 서비스가 지원됩니까?

고급 데이터 보호(백업 및 재해 복구) 및 FabricPool를 지원하는 하이브리드 클라우드 계층화는 추가 비용으로 선택할 수 있는 애드온 서비스입니다.



=== NetApp은 서비스를 통해 어떤 서비스 수준을 보장합니까?

NetApp 운영 시나리오에서 NetApp Keystone은 프로비저닝되는 스토리지에 대한 IOPS/TiB와 각 서비스 수준에 대한 지연 시간을 보장합니다.



=== Flex Subscription은 무엇에 매핑됩니까?

Flex Subscription은 단일 사이트 또는 단일 데이터 센터에 매핑되며 다양한 성능 서비스 수준으로 구성될 수 있습니다.



=== 익스트림 계층화 및 프리미엄 계층화 성능 레벨의 이점은 무엇입니까?

최고 수준의 계층화 및 프리미엄 계층화의 성능 수준을 통해 계층화가 이루어짐에 따라 스토리지 설치 공간과 관련 비용을 절감할 수 있습니다. NetApp은 데이터의 25%가 핫 데이터라고 가정하며, 나머지 75%는 사용 빈도가 적거나 콜드 스토리지로 이동합니다. 또한 사용 현황 보고서를 확인하여 데이터 액세스 빈도를 파악하고 해당 정보를 기반으로 계층화 서비스를 설정할 수 있습니다.



=== 파트너가 NetApp에서 고객에게 구입한 것보다 더 많은 용량을 판매할 수 있습니까?

테넌트 가입은 파트너가 구입한 용량에 의해 제한되지 않습니다. 파트너는 NetApp에서 고객에게 판매한 용량보다 더 많은 용량을 판매할 수 있습니다. 구입한 용량을 초과하는 용량을 초과 할당이라고 합니다.



=== 고객 툴과 통합하기 위해 API가 제공됩니까?

예, RESTful API를 자체 애플리케이션에 통합할 수 있습니다. 지원 > API Documentation * 으로 이동하여 Flex Subscription 서비스에 대한 API 설명서를 확인하십시오. 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/us-en/keystone/seapiref_overview_of_netapp_service_engine_apis.html["Keystone 유연한 구독 API 가이드"].



=== 버스트 용량이란?

사용량을 커밋된 용량보다 20% 이상 증가 및 감소시킬 수 있습니다. 최대 용량 사용량은 매일 측정되며 사용 시에만 비용이 청구됩니다. 예를 들어, 커밋된 용량이 100TiB인 경우 최대 120TiB까지 늘릴 수 있습니다.



=== 버스트 사용에 대한 프리미엄 요금이 있습니까?

약정 용량의 최대 20%에 해당하는 버스트 용량 사용량은 약정 용량과 동일한 비율로 청구되며, 약정 용량의 20% 이상을 사용하는 경우 50% 프리미엄 요금입니다.



=== 버스트 용량의 이점은 무엇입니까?

버스트 용량은 장기간에 걸쳐 커밋하는 것에 비해 필요할 때 스토리지를 사용할 수 있는 유연성을 제공합니다.



=== 테넌트에 버스트 용량은 어떻게 할당됩니까?

최대 용량은 파트너에게 할당되며 파트너는 요구사항에 따라 고객에게 추가로 할당합니다.



=== 커밋된 용량 및 버스트 용량 사용량을 어디에서 확인할 수 있습니까?

NetApp Service Engine에는 커밋된 용량에 대해 사용된 용량을 보고하는 대시보드가 내장되어 있습니다.



=== 약정 용량 사용량의 특정 비율에 도달하면 알림이 표시됩니까?

예. 관리 툴에서 NetApp 서비스 엔진 대시보드를 통해 용량 사용에 대한 알림을 제공합니다.



=== Flex Subscription 사용량은 어떻게 볼 수 있습니까?

NetApp Service Engine은 구독하는 모든 서비스와 소비되는 양이 포함된 대시보드 보기를 제공합니다. NetApp 서비스 엔진에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/keystone/sewebiug_overview.html["여기"].



=== 서비스와 관련된 문제를 어떻게 보고합니까?

다음과 같은 다양한 채널을 통해 NetApp Keystone 지원을 받을 수 있습니다.

* 지원 이메일: mailto:keystone.services@netapp.com[keystone.services@netapp.com^]
* 에스컬레이션 이메일: mailto:keystone.escalations@netapp.com[keystone.escalations@netapp.com^]




=== 새 스토리지 서비스를 주문할 수 있습니까?

예. NetApp Service Engine 포털에서 새로운 스토리지 서비스 또는 스토리지 서비스 확장을 요청할 수 있습니다. 이 요청은 NetApp Keystone 운영 팀에서 처리한 후 사용할 수 있도록 합니다.



=== 스토리지 서비스 약속을 즉시 확인할 수 있습니까?

요청된 용량의 양에 따라 용량이 이미 배포되었는지 또는 추가 장비를 배송 및 설치해야 하는지 여부가 결정됩니다.



=== 계층 간에 워크로드를 이동할 수 있습니까?

예. 워크로드가 이동하는 계층에 사용자가 가입한 경우 계층 간에 워크로드를 이동할 수 있습니다. 하지만 성능이 저하될 수 있으므로 상위 계층에서 하위 계층으로 이동하는 것은 권장되지 않습니다. 이 프로세스는 파일 공유를 편집하고 서비스 수준 설정을 변경하는 것만으로 수행됩니다.



=== 어떤 소프트웨어 버전(예: ONTAP)이 기본값으로 설치되어 있습니까?

서비스 계층에 따라(예: 파일 및 블록 서비스가 포함된 ONTAP, 블록용 SANtricity 및 객체용 StorageGRID) 지원 팀은 보안 또는 기능 문제 없이 가장 안정적인 최신 릴리즈를 설치합니다.
