---
sidebar: sidebar 
permalink: nkfsosm-keystone-and-aiq.html 
keywords: netapp, keystone, aiq keystone customers, Active IQ, Digital Advisor 
summary: 고객이 Active IQ Keystone에 대해 확인할 수 있는 내용 
---
= Active IQ 디지털 어드바이저에서 유연한 구독 고객은 무엇을 볼 수 있습니까?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 유연한 구독(유연한 구독) 서비스를 구독한 경우 Active IQ 디지털 자문(디지털 자문) 대시보드에서 사용 보고서 및 그래프를 볼 수 있습니다.

Digital Advisor에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/us-en/active-iq/index.html["Digital Advisor 설명서"].

사이트에 NetApp Service Engine이 기본적으로 설치되어 있는 경우 Digital Advisor 외에도 NetApp Service Engine 인터페이스를 통해 소비 차트를 볼 수 있습니다. 그러나 고객이 관리하는 환경에서는 NetApp Service Engine 인터페이스에 액세스할 수 없으며, Digital Advisor 대시보드를 통해서만 용량 차트와 사용 보고서를 볼 수 있습니다. 고객이 관리하는 환경에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/keystone/nkfsosm_overview.html["운영 모델, 역할 및 책임"]

사이트에서 메트릭 데이터 수집 간격은 5분입니다.

고객은 Flex Subscription 서비스에 가입한 경우 Digital Advisor에서 다음 정보를 볼 수 있습니다.

* * Keystone Flex Subscription * 위젯: Digital Advisor에 로그인한 경우 구입한 Flex Subscription 서비스에 대한 용량 사용을 요약하는 * Keystone Flex Subscription * 위젯을 볼 수 있습니다.


자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/active-iq/view_keystone_capacity_utilization.html["NetApp Keystone 유연한 구독으로 용량 활용도를 확인할 수 있습니다"].

Keystone 구독 * 탭에 대한 자세한 내용은 _Digital Advisor 대시보드 및 Flex Subscription_에 대한 보고를 참조하십시오.
