---
sidebar: sidebar 
permalink: nkfsosm_data_protection.html 
keywords: netapp, keystone, data, protection, 
summary: 데이터 보호 
---
= 데이터 보호
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Keystone 유연한 구독(Flex Subscription) 데이터 보호 서비스는 데이터를 백업할 수 있으며 필요한 경우 복구할 수 있습니다. 사용 가능한 데이터 보호 서비스는 다음과 같습니다.

* 디스크 및 공유의 스냅샷입니다
* 디스크 및 공유 백업(구독의 일부로 데이터 보호 서비스 필요)
* 디스크 및 공유의 재해 복구(구독의 일부로 데이터 보호 서비스 필요)



NOTE: 백업 및 재해 복구 서비스는 추가 서비스로 제공되며 Snapshot은 기본 스토리지 서비스의 일부로 제공됩니다.

|===
|  | 단일 영역 스냅샷(기본 스토리지 서비스의 일부로 사용 가능) | 다중 지역 백업(데이터 보호 애드온) | 다중 지역 재해 복구(데이터 보호 애드온) 


| 사용 사례 | 인프라 손실이나 장애가 아닌 사용자 또는 애플리케이션 데이터의 삭제 또는 손상 위험을 완화하십시오 | 인프라 손실 또는 장애로 인해 운영 볼륨의 데이터가 완전히 손실될 위험을 완화하십시오 | 복구 시간 목표를 통해 인프라 손실 또는 장애로 인해 기본 볼륨에서 데이터가 완전히 손실될 위험을 완화하십시오 


| 정책 | 매시간, 매일, 매주 및 매월 | 시간별, 일별, 주별 및 월별 스냅샷을 기준으로 보존할 백업 수입니다 | 1시간, 4시간, 매일 


| 토폴로지 | 소스만 | 백업 | 비동기식 복제 타겟 


| 대상 복제 서비스 수준 ^1^ | 해당 없음 | 표준 | Primary와 동일합니다 
|===
^1^가입될 추가 스토리지 용량입니다


NOTE: 기본 Flex Subscription 서비스에 가입해도 데이터가 자동으로 백업되지는 않습니다. 추가 데이터 보호 서비스에 가입하고 데이터 백업 및 재해 복구 서비스에 맞게 시스템을 구성해야 합니다. 스토리지 시스템이 Flex Subscription 서비스로 관리되지 않는 경우에도 NetApp은 스토리지 시스템의 데이터 보호를 지원하며 Flex Subscription 서비스와 연결될 수 있도록 지원합니다. 그러나 NetApp은 백업 실패에 대한 책임을 지지 않습니다.
