---
sidebar: sidebar 
permalink: nkfsfaq_service_offer_details.html 
keywords: netapp, keystone, service, offer, details, 
summary: 서비스 제공 세부 정보 
---
= Keystone 서비스 오퍼링
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 질문은 NetApp Keystone Keystone 서비스 오퍼링에 대한 빈번한 쿼리에 대한 답변을 제공합니다.

* 커밋된 최소 용량은 얼마입니까? *

NetApp Keystone 구독 서비스에 대해 커밋된 최소 용량은 한 개 이상의 서비스 계층에 대해 사이트당 100TiB입니다.

* Keystone 서비스 계약의 일반적인 기간은 얼마입니까? *

Keystone 서비스는 12, 24 및 36개월 기간을 제공합니다.

* 스토리지에 액세스하는 방법은 무엇입니까? *

NetApp에서 운영하는(표준) 모델에서는 스토리지 컨트롤러(ONTAP System Manager 또는 시스템에 대한 관리 액세스)가 NetApp이 소유 및 관리합니다. Active IQ Digital Advisor UI를 통해서만 스토리지를 모니터링할 수 있습니다.
Active IQ 디지털 어드바이저 UI가 주로 청구 기능에 사용되는 고객 관리형(또는 Lite) 구축에서 Active IQ Unified Manager 및 ONTAP System Manager와 같은 스토리지 컨트롤러에 액세스하고 ONTAP 클러스터에 직접 액세스할 수 있습니다.

* 서비스를 어떻게 관리합니까? *

어떤 요구 사항이든 지원 티켓을 올릴 수 있습니다.

* 구독에서 커밋된 용량을 어떻게 늘릴 수 있습니까? *

귀하의 NetApp Keystone 성공 관리자를 통해.

* 용량을 늘리면 용어가 확장됩니까? *

가입 후 마지막 90일 이내에 요청이 이루어지면 최소 12개월 동안 기간이 연장되어야 하는 경우를 제외하고 모든 추가 사항은 기존 기간 동안 상호 적용됩니다.

* 가입은 서로 상호 연계할 수 있습니까? *

아니요, 구독 조건은 서로 독립적입니다.

* 백업 스토리지를 기존 구독에 추가할 수 있습니까? *

백업 활용 사례의 경우 표준 또는 가치 서비스 수준을 비롯한 기존 또는 새로운 서비스 수준에 대한 기존 구독에 용량을 추가할 수 있습니다. 기존 구독의 기간은 변경되지 않습니다. 그러나 한 가지 주의해야 할 점이 있습니다. 즉, 가입 기간의 마지막 90일(서브스크립션 종료 전 마지막 90일) 내에 용량을 추가하려는 경우 최소 1년 동안 서브스크립션을 갱신해야 합니다.

* 새 가입은 새로운 연례에 따라 유연하게 사용할 수 있습니까? *

예. 새 구독은 기존 구독과 별도로 새 용어를 사용할 수 있습니다.

* 테넌트 구독 조건은 파트너의 구독 기간 이후에도 연장될 수 있습니까? *

테넌트 구독은 파트너의 현재 Keystone 서비스 기간 이상으로 확장될 수 있습니다. 구독이 생성될 때 및 사용 현황 보고서에 경고가 표시됩니다.

* 동일한 ONTAP 클러스터에서 여러 서브스크립션을 혼합할 수 있습니까? *

아니요. 각 클러스터는 특정 구독에 할당됩니다.

* 모니터링 및 작업은 누가 합니까? *

NetApp 운영 서비스의 경우, NetApp은 합의된 기대치에 따라 서비스를 제공할 수 있도록 인프라를 원격으로 모니터링하는 역할을 합니다.

파트너 운영 서비스의 경우 파트너는 합의된 기대치에 따라 서비스를 제공할 수 있도록 인프라를 원격으로 모니터링할 책임이 있습니다.

고객 운영 서비스의 경우 고객은 인프라를 모니터링하고 NetApp에 문제를 제기할 책임이 있습니다.

* 서비스를 일찍 종료하면 어떻게 됩니까? *

최소 서비스 기간은 12개월입니다. 서비스를 일찍 취소하는 경우 잔여 금액을 선불로 지불해야 합니다.

* 초기 기간이 완료된 후 구매로 전환할 수 있는 기회가 있습니까? * 아니요 이 특가에는 구매로 전환할 수 있는 옵션이 포함되어 있지 않습니다. 또한 이전에 구매한 NetApp 제품은 이 프로그램의 범위를 벗어납니다.

* 특정 소프트웨어 버전을 요청할 수 있습니까? *

아니요 NetApp Keystone은 모든 고객 기반에서 소프트웨어 버전을 표준화했습니다.

* 소프트웨어 업그레이드에 대한 정보를 받을 수 있습니까? *

예. 모든 유지 보수/업그레이드 작업은 NetApp Keystone 성공 관리자가 고객과 상호 합의된 시간에 전달하고 스케줄합니다.
