---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: NetApp Keystone 서비스
    url: "/index.html"
    entries:
    - title: 서비스 약관 및 설명
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: 서비스 용량 정의
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Keystone의 서비스 수준
        url: "/nkfsosm_performance.html"
      - title: 서비스 수준 메트릭 및 정의
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Keystone의 적응형 서비스 품질
        url: "/aqos-kfs.html"
      - title: 청구
        url: "/nkfsosm_kfs_billing.html"
      - title: 데이터 보호
        url: "/nkfsosm_data_protection.html"
      - title: 계층화
        url: "/nkfsosm_tiering.html"
      - title: 반품 불가 디스크
        url: "/nkfsosm_nrd.html"
      - title: 미국 시민 지원
        url: "/nkfsosm_uscs.html"
      - title: Keystone과 Equinix
        url: "/nkfsosm_equinix.html"
    - title: 운영 모델 및 책임
      url: "/nkfsosm_overview.html"
    - title: 테넌시 및 멀티 테넌시
      url: "/nkfsosm_tenancy_overview.html"
    - title: Keystone 인프라
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: 사이트 요구 사항
      url: "/nkfsosm_site_requirements.html"
    - title: 운영
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone 및 Active IQ 디지털 자문
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Active IQ 디지털 어드바이저에서 보고서를 보고 생성합니다
        url: "/aiq-keystone-details.html"
  - title: 릴리즈 노트
    entries:
    - title: 새로운 소식
      url: "/rn_whats_new.html"
    - title: 해결된 문제
      url: "/rn_fixed_issues.html"
    - title: 알려진 문제
      url: "/rn_known_issues.html"
  - title: Keystone 구독 FAQ
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Keystone 구독
      url: "/nkfsfaq_keystone_subscription.html"
    - title: 서비스 제공 세부 정보
      url: "/nkfsfaq_service_offer_details.html"
    - title: 운영 모델
      url: "/nkfsfaq_operating_models.html"
  - title: 법적 고지
    url: "/legal-notices.html"
