---
sidebar: sidebar 
permalink: rn_whats_new.html 
keywords: 'netapp, keystone, release notes, new features, what"s new,' 
summary: NetApp 서비스 엔진의 새로운 기능 
---
= 이 NetApp Keystone 서비스 릴리스의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
릴리스 노트는 NetApp Keystone 서브스크립션 서비스에 도입된 새로운 기능 및 향상된 기능과 알려진 제한 사항 및 수정 사항을 알려줍니다.

Keystone 가입 서비스를 통해 제공되는 향상된 기능을 지원하기 위해 NetApp 서비스 엔진 다양한 릴리즈에는 다음 기능이 도입되었습니다.



== NetApp Service Engine 2.2에서 도입된 기능

이 릴리즈의 새로운 기능에는 청구서, 용량 활용률, 서비스 요청 및 알림에 대한 새로운 위젯을 위한 개선된 대시보드가 포함됩니다. 이 릴리스에는 청구 및 알림 관리를 위한 새로운 화면 및 구독한 서비스 메뉴의 이름을 클라우드 서비스로 바꾸는 기능도 포함되어 있습니다.



=== 향상된 대시보드 뷰

NetApp Service Engine 대시보드는 다음과 같은 새 구성 요소를 포함하도록 재설계되었습니다.

* * 용량 활용도 * 구독한 서비스에 사용된 용량을 확인하는 데 사용됩니다.
* * 모든 구독에 대해 집계된 월별 요금을 보기 위한 월별 요금(청구) *.
* * 알림 * 사용자 환경에서 가장 최근의 알림 요약을 볼 수 있습니다.
* * 서비스 요청 * 사용자 환경에서 생성된 최신 서비스 요청 목록을 표시합니다.




=== 새 청구 화면

새로운 * 청구 * 화면이 추가되어 간편하게 액세스할 수 있고 과거 청구 데이터를 계산할 수 있습니다. 이 화면에서는 모든 구독한 서비스와 관련된 월별 요금을 전체적으로 볼 수 있습니다.

대시보드의 * Monthly Billes * 위젯이나 * administration > Billing * 에서 이 화면으로 이동하여 구독한 모든 서비스에 대한 월별 구독 수준의 요금 분업을 확인할 수 있습니다. 청구 데이터는 약정 및 버스트 용량 사용량을 기준으로 하며, 이전 개월 동안 사용할 수 있습니다.



=== New Alerts(새 경고) 화면

이 릴리즈에는 시스템에서 생성하고 사용자가 생성한 모든 경고가 나열된 새 * Alerts * 화면이 도입되었습니다. 또한 이 화면을 통해 사용자 환경과 관련된 중요 이벤트에 대한 사용자 지정 경고 메시지를 만들어 다른 사용자에게 전달할 수 있습니다. 필요에 따라 알림을 보고 해제할 수 있습니다.



=== 향상된 사용자 인터페이스

NetApp Service Engine 사용자 인터페이스에서 다음과 같은 개선 사항이 있었습니다.

* 왼쪽 탐색 창의 * Dashboard * 메뉴는 대시보드에 액세스할 수 있는 직관적인 탐색 지점을 제공합니다.
* 왼쪽 탐색 창에 있는 * Subscribed Services * 메뉴의 이름이 * Cloud Services * 로 변경되었습니다. ++




== NetApp Service Engine 2.1에 도입된 기능

이 릴리즈의 새로운 기능에는 Keystone 환경에서 멀티 테넌시 지원 및 저렴한 로컬 또는 클라우드 계층으로 비활성 데이터를 쉽게 이동할 수 있는 계층화 기능이 포함됩니다.



=== 서비스 공급자를 위한 Keystone 가입 서비스 소개

이제 NetApp Service Engine은 서비스 공급자를 통해 멀티 테넌트(multi-tenant) 환경의 관리를 지원합니다. 자체 서브스크립션을 보유한 고객을 프로비저닝, 보고, 청구 및 관리하는 기능을 수행할 수 있습니다. 이 기능을 지원하기 위해 다음과 같은 기능이 향상되었습니다.

* * 대시보드: * 대시보드에는 서비스 계층, 각 서비스 수준에 대한 용량 사용, 특정 구독 번호에 대한 추가 데이터 보호 서비스 등의 스토리지 구독에 대한 정보가 표시됩니다. 서비스 공급자는 NetApp Keystone 구독 및 테넌트 구독의 세부 정보를 볼 수 있습니다. 테넌트 관리자는 테넌시에 대한 모든 테넌트 구독의 세부 정보를 볼 수 있습니다.
* * 보고: * NetApp Keystone 가입 사용량과 테넌트 사용량에 대한 용량 및 성능 보고서를 생성할 수 있습니다. 파트너 관리자는 * Reports * > * Keystone Usage * 에서 구독 사용량에 대한 용량 보고서를 볼 수 있습니다. 파트너 관리자는 * Reports * > * Tenant Usage * / * Capacity Usage * 에서 특정 테넌트의 용량 사용 보고서를 볼 수 있습니다. 테넌트 관리자는 * Reports * > * Tenant Usage * 에서 Tenancy 보고서를 볼 수 있습니다.
* * 가입: * 파트너 관리자는 * 가입 * > * Keystone 가입 * 및 * 가입 * > * 테넌트 구독 * 에서 구독 및 테넌트 구독을 각각 확인하고 업데이트할 수 있습니다. 테넌트 관리자는 테넌트 구독만 볼 수 있습니다.
* * 사용자: * 역할에 따라 필요에 따라 테넌시에 있는 신규 또는 기존 사용자에게 권한을 할당할 수 있습니다. 이 역할은 NetApp 관리자, 읽기 전용 권한이 있는 NetApp 관리자, 파트너 관리자 또는 테넌트 관리자일 수 있습니다. 파트너 관리자는 파트너 관리자 또는 테넌트 관리자 역할만 새 사용자에게 할당할 수 있습니다. 테넌트 관리자 사용자는 테넌트 관리자 역할만 다른 사용자에게 할당할 수 있습니다.
* * 네트워크 메뉴: * 파트너 관리자는 테넌시에 대해 정의된 네트워크를 볼 수 있습니다. 또한 * networks * > * subnets * 에서 서브테넌트와 존에 대한 서브넷을 생성할 수 있습니다. 이는 최종 고객 또는 하위 테넌트가 스토리지를 프로비저닝하는 동안 필요합니다.




=== 계층화

NetApp Keystone Keystone 서비스에는 NetApp FabricPool 기술을 활용하는 계층화 기능이 포함됩니다. NetApp에서 소유, 구축, 관리하는 콜드 스토리지에 덜 사용되는 데이터를 식별하고 계층화합니다. 익스트림 계층화 또는 프리미엄 계층화 서비스 수준에 가입하여 계층화를 선택할 수 있습니다.

새 계층화 서비스 수준에 대한 새로운 속성 값을 포함하도록 다음 API가 수정되었습니다.

* 파일 서비스 API
* 블록 저장소 API


자세한 내용은 다음 링크를 참조하십시오.

* link:nkfsosm_tiering.html["계층화"]
* link:nkfsosm_performance.html["서비스 레벨"]


{SP} + {SP} + {SP}입니다



== NetApp Service Engine 2.0.1에 도입된 기능

이 릴리즈의 새로운 기능은 다음과 같습니다.



=== Cloud Volumes Services for Google Cloud Platform으로 확장 지원

이제 NetApp 서비스 엔진은 Azure NetApp Files에 대한 기존 지원 외에도 GCP(Cloud Volumes Services for Google Cloud Platform) 를 지원할 수 있습니다. 이제 구독 서비스를 관리하고 NetApp Service Engine에서 Google Cloud Volumes를 프로비저닝 및 수정할 수 있습니다.


NOTE: Cloud Volumes Services에 대한 구독은 NetApp 서비스 엔진 외부에서 관리됩니다. 클라우드 서비스에 연결할 수 있도록 관련 자격 증명이 NetApp 서비스 엔진에 제공됩니다.



=== NetApp 서비스 엔진 외부에서 프로비저닝된 오브젝트를 관리할 수 있습니다

고객 환경에 이미 존재하고 NetApp 서비스 엔진에 구성된 스토리지 VM에 속하는 볼륨(디스크 및 파일 공유)은 이제 NetApp Keystone 서브스크립션의 일부로 보고 관리할 수 있습니다. 이제 NetApp 서비스 엔진 외부에서 프로비저닝된 볼륨이 * Shares * 및 * Disks * 페이지에 적절한 상태 코드가 표시됩니다. 백그라운드 프로세스는 주기적으로 실행되며 NetApp Service Engine 인스턴스 내에서 외부 워크로드를 가져옵니다.

가져온 디스크 및 파일 공유가 NetApp Service Engine에서 기존 디스크 및 파일 공유와 동일한 표준에 없을 수 있습니다. 가져오기 후 이러한 디스크와 파일 공유는 Non-Standard 상태로 분류됩니다. 지원 > 서비스 요청 > 새 서비스 요청 * 에서 서비스 요청을 제기하면 NetApp 서비스 엔진 포털을 통해 서비스 요청을 표준화 및 관리할 수 있습니다.



=== SnapCenter와 NetApp 서비스 엔진 통합

SnapCenter 서비스 엔진과 NetApp 통합 시, 이제 NetApp 서비스 엔진 인스턴스 외부에 있는 SnapCenter 환경에서 생성된 스냅샷에서 디스크 및 파일 공유를 클론 복제할 수 있습니다. NetApp 서비스 엔진 포털의 기존 스냅샷에서 파일 공유 또는 디스크를 클론 복제하는 동안 이러한 스냅샷이 선택 항목에 나열되어 있습니다. 수집 프로세스는 백그라운드에서 주기적으로 실행되어 NetApp 서비스 엔진 인스턴스 내에 스냅샷을 가져옵니다.



=== 백업 유지 관리를 위한 새 화면

새로운 * Backup * 화면에서는 사용자 환경에서 생성된 디스크 및 파일 공유의 백업을 보고 관리할 수 있습니다. 백업 정책을 편집하고 소스 볼륨과의 백업 관계를 끊은 다음 모든 복구 지점이 있는 백업 볼륨을 삭제할 수도 있습니다. 이 기능을 사용하면 소스 볼륨이 삭제되어도 나중에 복구할 수 있도록 백업을 고립된 백업으로 유지할 수 있습니다. 특정 복구 지점에서 파일 공유 또는 디스크를 복원하는 경우 * 지원 > 서비스 요청 > 새 서비스 요청 * 에서 서비스 요청을 제기할 수 있습니다.



=== CIFS 공유에 대한 사용자 액세스를 제한하는 데 필요한 프로비저닝

이제 CIFS(SMB) 또는 다중 프로토콜 공유에서 사용자 액세스를 제한하는 ACL(액세스 제어 목록)을 지정할 수 있습니다. ACL에 추가할 AD(Active Directory) 설정에 따라 Windows 사용자 또는 그룹을 지정할 수 있습니다.



== NetApp Service Engine 2.0에서 도입된 기능

이 릴리즈의 새로운 기능은 다음과 같습니다.



=== MetroCluster 지원

NetApp 서비스 엔진은 MetroCluster 구성으로 구성된 사이트를 지원합니다. MetroCluster는 지속적으로 사용 가능한 스토리지를 위해 동기식 미러를 사용하여 RPO(복구 시점 목표) 0 또는 RTO(복구 시간 목표) 0를 제공하는 ONTAP의 데이터 보호 기능입니다. MetroCluster 지원은 NetApp 서비스 엔진 내의 동기식 재해 복구 기능으로 이어집니다. MetroCluster 인스턴스의 각 면은 별도의 영역으로 등록되며, 각 영역에는 데이터 보호 고급 속도 계획이 포함된 자체 구독이 있습니다. MetroCluster 지원 영역에서 생성된 공유 또는 디스크는 두 번째 존에 동기식으로 복제됩니다. 복제된 영역의 소비는 스토리지가 프로비저닝되는 영역에 적용되는 데이터 보호 고급 속도 계획을 따릅니다.



=== Cloud Volumes Services 지원

이제 NetApp 서비스 엔진에서 Cloud Volumes Services를 지원할 수 있습니다. 이제 Azure NetApp Files를 지원할 수 있습니다.


NOTE: Cloud Volumes Services에 대한 구독은 NetApp 서비스 엔진 외부에서 관리됩니다. 클라우드 서비스에 연결할 수 있도록 관련 자격 증명이 NetApp 서비스 엔진에 제공됩니다.

NetApp 서비스 엔진은 다음을 지원합니다.

* Cloud Volumes Services 볼륨 프로비저닝 또는 수정(스냅샷 생성 기능 포함)
* Cloud Volumes Services 영역에 데이터 백업
* NSE 인벤토리에서 Cloud Volumes Services 볼륨 보기
* Cloud Volumes Services 사용량 보기




=== 호스트 그룹

NetApp 서비스 엔진은 호스트 그룹의 사용을 지원합니다. 호스트 그룹은 FC 프로토콜 호스트 WWPN(Worldwide Port Name) 또는 iSCSI 호스트 노드 이름(IQN) 그룹입니다. 호스트 그룹을 정의하고 디스크에 매핑하여 디스크에 액세스할 수 있는 이니시에이터를 제어할 수 있습니다. 호스트 그룹은 모든 디스크에 대해 개별 이니시에이터를 지정해야 하는 필요성을 대체하며 다음을 허용합니다.

* 동일한 이니시에이터 세트에 추가 디스크가 표시됩니다
* 여러 디스크에 걸쳐 이니시에이터 세트를 업데이트합니다




=== 최대 사용량 및 알림

일부 NetApp Service Engine - 지원되는 스토리지 구독을 통해 고객은 약정 용량 이상의 버스트 용량을 사용할 수 있습니다. 이 용량은 할당된 용량 이상의 별도 비용이 청구됩니다. 사용자는 버스트 용량을 언제 사용해야 하는지 또는 사용량과 비용을 제어하기 위해 언제 사용했는지 이해하는 것이 중요합니다.



==== 제안된 변경으로 인해 버스트 용량이 발생할 경우 알림

제안된 프로비저닝에서 구독이 급증하도록 야기되는 변경 사항을 표시하는 알림입니다. 사용자는 구독이 급증하거나 작업을 계속하지 않도록 선택할 수 있습니다.



==== 버스트 가입 시 알림

구독이 버스트 상태일 때 알림 배너가 표시됩니다.



==== 용량 보고서에 버스트 사용량이 표시됩니다

구독이 버스트 된 일수와 사용된 버스트 용량의 수량을 보여 주는 용량 보고서입니다.



=== 성능 보고서

NetApp 서비스 엔진 웹 인터페이스의 새로운 성능 보고서에는 개별 디스크 또는 공유 성능에 대한 정보가 다음 성능 측정값에 표시됩니다.

* IOPS/TiB(Teibyte당 초당 입출력 작업 수): 스토리지 디바이스에서 입출력 작업이 수행되는 속도(IOPS)입니다.
* 처리량(Mbps 단위): 스토리지 미디어 간 데이터 전송 속도(MB/초)입니다.
* 지연 시간(ms): 디스크 또는 공유의 읽기 및 쓰기 평균 시간(밀리초)입니다.




=== 구독 관리

구독 관리가 향상되었습니다. 이제 다음을 수행할 수 있습니다.

* 데이터 보호 애드온을 요청하거나 구독 또는 서비스에 대한 데이터 보호 애드온에 대한 추가 용량을 요청합니다
* 데이터 보호 사용 용량 보기




=== 비용 청구 향상

이제 청구 에서는 ONTAP(파일 및 블록) 스토리지의 스냅샷 사용을 측정하고 청구하는 기능을 지원합니다.



=== 숨겨진 CIFS 공유

NetApp Service Engine은 숨겨진 CIFS 공유를 생성할 수 있도록 지원합니다.
