---
sidebar: sidebar 
permalink: seapiref_jobs.html 
keywords: netapp, keystone, jobs, 
summary: Keystone 작업 API 
---
= 작업
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
작업 API를 사용하여 작업 세부 정보를 검토합니다. 작업 작업에 대한 자세한 내용은 작업 개체 API 및 비동기 프로세스 를 참조하십시오.



=== 작업을 검색합니다

다음 표에 나열된 방법을 사용하여 모든 작업 또는 작업의 하위 집합을 검색할 수 있습니다. Tenant_id를 지정하면 해당 Tenant에 속한 작업만 반환됩니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/일자리' | 작업을 검색합니다. | 'tenant_id': (선택 사항) 지정된 테넌트에 속한 블록 저장소를 반환합니다. '오프셋'과 '한계'는 를 참조하십시오 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 2625,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 1,
    "records": [
      {
        "id": "5ed72c8c6342e90001439d54",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-03T04:52:28.478Z",
        "updated": "2020-06-03T04:52:32.636Z",
        "object_id": "5ed72c8c6342e90001439d55",
        "object_type": "sg_buckets",
        "object_name": "test1234",
        "status": "successful",
        "status_detail": "Creation of s3 bucket 'test1234' completed successfully.",
        "last_error": "",
        "user_id": "5e85225af038943eb4b74684",
        "job_tasks": [
          {
            "id": "5ed72c8c6342e90001439d57",
            "job_id": "5ed72c8c6342e90001439d54",
            "action": "create",
            "driver": "storagegrid_ansible",
            "object_id": "5ed72c8c6342e90001439d55",
            "object_type": "sg_buckets",
            "resource_type": "sg_bucket",
            "status": "successful",
            "status_detail": "Worker completed task successfully.",
            "last_error": "",
            "user_id": "5e85225af038943eb4b74684",
            "request_payload": {
              "grid_account_id": "05336917559886003354",
              "grid_admin_base_url": "https://sggmi-dev.dev.ausngs.netapp.au/api/v3",
              "org_password": "netapp01",
              "org_username": "root",
              "s3_bucket_name": "test1234"
            }
          }
        ]
      }
    ]
  }
}
....


==== 작업 ID별로 작업을 검색합니다

다음 표에 나열된 방법을 사용하여 ID별로 작업을 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/jobs/{id}' | ID별로 작업을 검색합니다. | id(string): 작업의 고유 식별자입니다. 
|===
필요한 요청 본문 속성: '작업 식별자'

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66f18e09a74c0001b89640",
        "action": "create",
        "job_summary": "Create S3 bucket for Sub Tenant",
        "created": "2020-03-10T01:46:54.097Z",
        "updated": "2020-03-10T01:46:57.664Z",
        "object_id": "5e66f18e09a74c0001b89641",
        "object_type": "sg_buckets",
        "status": "successful",
        "status_detail": "Creation of s3 bucket 'mys3bucket' completed successfully.",
        "last_error": "",
        "user_id": "5bbee380a2df7a04d43acaee",
        "job_tasks": [
          {
            "id": "5e66f18e09a74c0001b89642",
            "job_id": "5e66f18e09a74c0001b89640",
            "action": "create",
            "driver": "storagegrid_ansible",
            "object_id": "5e66f18e09a74c0001b89641",
            "object_type": "sg_buckets",
            "resource_type": "sg_bucket",
            "status": "successful",
            "status_detail": "Worker completed task successfully.",
            "last_error": "",
            "user_id": "5bbee380a2df7a04d43acaee",
            "request_payload": {
              "grid_account_id": "47490102387197219062",
              "grid_admin_base_url": "https://sggmi-dev.dev.ausngs.netapp.au/api/v3",
              "org_password": "netapp01",
              "org_username": "root",
              "s3_bucket_name": "mys3bucket"
            }
          }
        ]
      }
    ]
  }
}
....


=== 작업 객체 API 및 비동기 프로세스

일부 API 호출, 특히 리소스를 추가하거나 수정하는 데 사용되는 호출은 다른 호출보다 완료하는 데 시간이 오래 걸릴 수 있습니다. NetApp 서비스 엔진은 이러한 오래 실행되는 요청을 비동기식으로 처리합니다.

비동기적으로 실행되는 API 호출을 수행한 후 HTTP 응답 코드 202는 요청이 성공적으로 유효성 확인 및 승인되었지만 아직 완료되지 않았음을 나타냅니다. 요청은 클라이언트에 대한 초기 HTTP 응답 후 계속 실행되는 백그라운드 작업으로 처리됩니다. 응답에는 고유한 식별자를 포함하여 요청을 고정하는 작업 객체가 포함됩니다.



==== API 요청과 관련된 작업 객체를 쿼리합니다

HTTP 응답에서 반환된 작업 개체에는 여러 속성이 포함되어 있습니다. 상태 속성을 쿼리하여 요청이 성공적으로 완료되었는지 확인할 수 있습니다. 작업 오브젝트는 다음 상태 중 하나일 수 있습니다.

* 정상
* 경고
* partial_failures 를 선택합니다
* 오류


작업 객체를 폴링하여 작업의 터미널 상태를 감지할 때 성공 또는 실패 등 두 가지 기법을 사용할 수 있습니다.

* 표준 폴링 요청: 현재 작업 상태가 즉시 반환됩니다.
* 긴 폴링 요청: 작업 상태가 정상, 오류 또는 partial_failures로 이동하는 경우




==== 비동기 요청에 대한 단계입니다

다음 고급 절차를 사용하여 비동기 API 호출을 완료할 수 있습니다.

. 비동기 API 호출을 실행합니다.
. 요청을 성공적으로 수락했음을 나타내는 HTTP 응답 202 을 수신합니다.
. 응답 본문에서 작업 오브젝트의 식별자를 추출합니다.
. 루프 내에서 작업 객체가 터미널 상태 정상, 오류 또는 partial_failures에 도달할 때까지 기다립니다.
. 작업의 터미널 상태를 확인하고 작업 결과를 가져옵니다.

