---
sidebar: sidebar 
permalink: seapiref_subtenants.html 
keywords: netapp, keystone, subtenants, 
summary: Keystone 서브테넌트 
---
= 하위 테넌트
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 표에 나열된 방법을 사용하여 하위 테넌트를 검색, 생성, 수정 및 삭제할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/서브테넌트' | 하위 테넌트 검색 


| "내려가세요 | '/v2.1/서브테넌트/{id}' | 서브테넌트 ID로 서브테넌트를 검색합니다. 


| POST를 누릅니다 | '/v2.1/아세입자' | 새 서브테넌트를 생성합니다. 


| 'Put' | '/v2.1/서브테넌트/{id}' | 서브테넌트의 세부 정보를 수정합니다. 서브테넌트의 이름을 수정할 수 있습니다. 


| "삭제" | '/v2.1/서브테넌트/{id}' | 서브테넌트를 삭제합니다. 
|===


=== 서브테넌트 특성

다음 표에는 서브테넌트 속성이 나와 있습니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 서브테넌트의 고유 식별자입니다. 


| 이름 | 문자열 | 서브테넌트 이름입니다. 


| '코드' | 문자열 | 서브테넌트를 나타내는 고객 지정(또는 기본값) 코드입니다. 


| 테넌트_id | 문자열 | 서브테넌트가 속해 있는 테넌트의 식별자입니다. 
|===


=== 모든 하위 테넌트를 검색합니다

다음 표에 나열된 방법을 사용하여 모든 하위 테넌트 또는 모든 하위 테넌트의 하위 집합을 검색할 수 있습니다. Tenant_id를 지정하면 해당 Tenant에 속한 서브테넌트만 반환됩니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/서브테넌트' | 하위 테넌트 검색 | 'tenant_id': (선택 사항) 지정된 테넌트에 속한 서브테넌트를 반환합니다. 오프셋 및 제한 - 참조 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 202,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "mysubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      },
      {
        "id": "5d9144f3869caefed0f39f82",
        "description": "",
        "name": "Mysubtenant2",
        "code": "myothersubtenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== ID로 서브테넌트를 검색합니다

ID로 서브테넌트를 검색하려면 다음 방법을 사용하십시오.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/서브테넌트/{id}' | ID로 지정된 서브테넌트를 검색합니다. | id(string): 서브테넌트의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "subtenantcode",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== 서브테넌트를 생성합니다

다음 표에 나열된 방법을 사용하여 서브테넌트를 생성합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/서브테넌트' | 새 서브테넌트를 생성합니다. | 없음 
|===
요청 본문 속성은 이름 코드 테넌트 ID입니다

* 요청 본문 예: *

....
{
  "name": "MySubtenant",
  "code": "mynewsubtenant",
  "tenant_id": "5ed5ac802c356a0001a735af"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== ID로 서브테넌트를 수정합니다

다음 표에 나열된 방법을 사용하여 ID별로 서브테넌트를 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/서브테넌트/{id}' | ID로 지정된 서브테넌트를 수정합니다. 서브테넌트 이름을 변경할 수 있습니다. | id(string): 서브테넌트의 고유 식별자입니다. 
|===
요청 본문 속성: 이름

* 요청 본문 예: *

....
{
  "name": "MyModifiedSubtenant"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


=== ID로 서브테넌트를 삭제합니다

다음 표에 나열된 방법을 사용하여 ID별로 서브테넌트를 삭제합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | '/v2.1/서브테넌트/{id}' | ID로 지정된 서브테넌트를 삭제합니다. | id(string): 서브테넌트의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
No content for succesful delete
....