---
sidebar: sidebar 
permalink: seapiref_@consumer@_administration_apis.html 
keywords: netapp, keystone, consumer, administration, apis, 
summary: 'Keystone(소비자) 관리 API' 
---
= (소비자) 관리 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
(소비자) 관리 API는 다음 작업을 수행할 수 있는 메서드로 구성됩니다.

* 로그인하고 암호를 설정한 다음 인증 토큰을 새로 고칩니다.
* 작업을 검색하고 작업 세부 정보를 봅니다.
+
을 참조하십시오 link:seapiref_jobs.html#retrieve-jobs["작업을 검색합니다"] 및 link:seapiref_jobs.html#retrieve-a-job-by-job-id["작업별 ID를 가져옵니다"].

* 영역 검색.
+
을 참조하십시오 link:seapiref_regions.html#retrieve-regions["영역 검색"] 및 link:seapiref_regions.html#retrieve-a-region-by-name["이름별로 지역을 조회한다"].

* 서비스 수준 검색
+
을 참조하십시오 link:seapiref_service_levels.html#retrieve-service-levels["서비스 수준 검색"] 및 link:seapiref_service_levels.html#retrieve-service-levels-by-name["이름별로 서비스 수준을 검색합니다"].

* 하위 테넌트와 함께 작업합니다.
+
참조:

+
** link:seapiref_subtenants.html#retrieve-all-subtenants["모든 하위 테넌트를 검색합니다"]
** link:seapiref_subtenants.html#retrieve-a-subtenant-by-id["ID로 서브테넌트를 검색합니다"]
** link:seapiref_subtenants.html#modify-a-subtenant-by-id["서브테넌트를 수정합니다"]
** link:seapiref_subtenants.html#delete-a-subtenant-by-id["ID로 서브테넌트를 삭제합니다"]


* 하위 테넌트와 함께 작업합니다.
+
참조:

+
** link:seapiref_tenants.html#retrieve-all-tenants["모든 테넌트를 검색합니다"]
** link:seapiref_tenants.html#retrieve-a-tenant-by-id["ID로 테넌트를 검색합니다"]
** link:seapiref_tenants.html#create-a-tenant["테넌트를 생성합니다"]
** link:seapiref_tenants.html#modify-the-tenant["테넌트를 수정합니다"]
** link:seapiref_tenants.html#delete-the-tenant["테넌트를 삭제합니다"]


* 사용자를 검색합니다.
+
link:seapiref_users.html#retrieve-all-users["모든 사용자를 검색합니다"], link:seapiref_users.html#retrieve-a-user-by-id["ID로 사용자를 검색합니다"], 및 link:seapiref_users.html#retrieve-a-user-by-user-name["사용자 이름으로 사용자를 검색합니다"].

* 영역 검색.
+
을 참조하십시오 link:seapiref_zones.html#retrieve-all-zones["모든 Zone을 조회한다"] 및 link:seapiref_zones.html#retrieve-a-zone-by-name["이름으로 Zone을 조회한다"]



다음 표에는 이 섹션에 나와 있는 소비자 API가 나와 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 


| POST를 누릅니다 | '/v2.1/auth/password' | 사용자의 암호를 설정합니다. 


| POST를 누릅니다 | '/v2.1/auth/password' | 인증 JWT를 새로 고칩니다. 


| POST를 누릅니다 | '/v2.1/auth/signin' | 로그인합니다. 


| "내려가세요 | '/v2.1/auth/regions' | 영역 검색. 


| "내려가세요 | '/v2.1/auth/regions/{name}' | 이름별로 영역을 검색합니다. 


| "내려가세요 | '/v2.1/auth/zone' | 영역 검색. 


| "내려가세요 | '/v2.1/auth/zones/{name}' | 이름별로 영역을 검색합니다. 


| "내려가세요 | '/v2.1/jobs/' | 작업을 검색합니다. 


| "내려가세요 | '/v2.1/jobs/{id}' | ID별로 작업을 검색합니다. 
|===


== 사용자 암호를 재설정합니다

다음 표에 나열된 방법을 사용하여 사용자 암호를 재설정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/auth/password' | 암호를 재설정합니다. | 없음 
|===
요청 본문 속성: 'username'(string), 'new_password'(string)

* 요청 본문 예: *

....
{
  "username": "MyName",
  "old_password": "oldPassword",
  "new_password": "newPassword"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5e61aa814559c20001df1a5f",
          "username": "MyName",
          "firstName": "MyFirstName",
          "lastName": "MySurname",
          "displayName": "CallMeMYF",
          "email": "user@example.com",
          "tenancies": [
            {
              "id": "5e5f1c4f253c820001877839",
              "name": "MyTenant",
              "code": "testtenantmh",
              "role": "user"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik15TmFtZSIsImV4cCI6MTU4MzgxNjg3MX0.ZuRXjDPVtc2pH-e9wqgmszVKCBYS2PLqux2YwQ5uoAM"
      }
    ]
  }
}
....


== 인증 토큰을 새로 고칩니다

다음 표에 나열된 방법을 사용하여 인증 토큰을 새로 고칩니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/auth/refresh' | 인증 토큰을 새로 고칩니다. | 없음 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5d914547869caefed0f3a00c",
          "username": "myusername",
          "firstName": "myfirstname",
          "lastName": "",
          "displayName": "Myfirstname Mysurname",
          "email": "",
          "tenancies": [
            {
              "id": "5d914499869caefed0f39eee",
              "name": "MyOrg",
              "code": "myorg",
              "role": "admin"
            },
            {
              "id": "5d9417aa869caefed0f7b4f9",
              "name": "ABCsafe",
              "code": "abcsafe",
              "role": "admin"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsbGlvdCIsImV4cCI6MTU4MzgxNzA2N30.FdKD3QhPoNdWdbMfZ0bzCMTHluIt6HNP311F482K9AY"
      }
    ]
  }
}
....


== 로그인합니다

다음 표에 나열된 방법을 사용하여 로그인합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/auth/signin' | 사용자로 로그인합니다. | 없음 
|===
요청 본문 속성: 'username'(string), 'new_password'(string)

* 요청 본문 예: *

....
{
  "username": "MyName",
  "password": "newPassword"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Authentication succeeeded.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5e61aa814559c20001df1a5f",
          "username": "MyName",
          "firstName": "MyFirstName",
          "lastName": "MySurname",
          "displayName": "CallMeMYF",
          "email": "user@example.com",
          "tenancies": [
            {
              "id": "5e5f1c4f253c820001877839",
              "name": "MyTenant",
              "code": "testtenantmh",
              "role": "user"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik15TmFtZSIsImV4cCI6MTU4MzgxNzQwMH0._u_UyYrzg_RewF-9ClIGoKQhfZYWrixZYBrsj1kh1hI"
      }
    ]
  }
}
....