---
sidebar: sidebar 
permalink: seapiref_regions.html 
keywords: netapp, keystone, regions, 
summary: 키스톤 영역 
---
= 지역
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
영역을 생성, 수정 및 삭제하려면 다음 표에 나열된 방법을 사용하십시오. 지역을 검색할 수 있는 API는 (소비자) 관리 API를 참조하십시오.

|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/지역' | 영역 가져오기. 


| "내려가세요 | '/v2.1/regions/{name}' | 이름별로 영역을 가져옵니다. 


| POST를 누릅니다 | '/v2.1/지역' | 새 영역을 만듭니다. 


| 'Put' | '/v2.1/regions/{name}' | 지역 세부 정보를 수정합니다. 


| "삭제" | '/v2.1/regions/{name}' | 영역을 삭제합니다. 
|===


=== 영역 속성

다음 표에서는 영역 특성을 보여 줍니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 영역의 고유 식별자입니다. 


| 이름 | 문자열 | 지역 이름입니다. 


| 설명 | 문자열 | 지역에 대한 설명입니다. 
|===


=== 영역 검색

다음 표에 나열된 방법을 사용하여 모든 영역 또는 영역의 하위 집합을 검색할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/지역' | 영역 검색. | '오프셋'과 '한계'는 를 참조하십시오 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 4,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 1,
    "records": [
      {
        "id": "5e7bf44daab46c00014ce77f",
        "name": "au-east8",
        "description": "This is the new region description",
        "zones": []
      }
    ]
  }
}
....


=== 이름별로 지역을 조회한다

다음 표에 나열된 방법을 사용하여 이름별로 영역을 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/regions/{name}' | 이름별로 지역을 조회한다. | 이름(string): 지역 이름. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "au-east1",
        "description": "string",
        "zones": [
          "au-east1-a"
        ]
      }
    ]
  }
}
....


=== 영역을 만듭니다

다음 표에 나열된 방법을 사용하여 영역을 만듭니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/지역' | 새 영역을 만듭니다. | 없음 
|===
요청 본문 속성: 이름

* 요청 본문 예: *

....
{
  "name": "MyRegionName",
  "description": "DescriptionOfMyRegion"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "Description": "DescriptionOfMyRegion",
        "user_id": "5bbee380a2df7a04d43acaee",
        "created": "0001-01-01T00:00:00Z",
        "tags": null
      }
    ]
  }
}
....


=== 영역을 수정합니다

다음 표에 나열된 방법을 사용하여 영역을 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/regions/{name}' | 이름으로 식별된 영역을 수정합니다. 영역의 이름과 설명을 변경할 수 있습니다. | 이름(string): 지역 이름. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
{
  "name": "MyRegionName",
  "description": "NewDescriptionOfMyRegion"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "description": "NewDescriptionOfMyRegion",
        "zones": []
      }
    ]
  }
}
....


=== 영역을 삭제합니다

다음 표에 나열된 방법을 사용하여 영역을 삭제합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | '/v2.1/regions{name}' | 이름으로 식별된 단일 영역을 삭제합니다. 영역 내의 모든 영역을 먼저 삭제해야 합니다. | 이름(string): 지역 이름. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
No content for succesful delete
....