---
sidebar: sidebar 
permalink: seapiref_subnets_apis.html 
keywords: netapp, keystone, subnets, networks, apis 
summary: Keystone 네트워크 API 
---
= 서브넷 API를 사용하여 네트워크 구성을 정의합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
서브넷 API를 사용하여 서브테넌트 및 존에 대한 서브넷을 보고 생성할 수 있습니다. 네트워크 구성을 정의하는 데 사용할 수 있습니다.

[cols="1,1,3,2"]
|===
| HTTP 동사 | 경로 | 설명 | 필수 매개 변수/요청 본문 


 a| 
"내려가세요
 a| 
"/v2.1/Tenants/{tenant_id}/" zones/{zone_name}/subnets"
| 테넌트 및 영역의 모든 서브넷 객체를 검색할 수 있습니다. VLAN, 서브테넌트, 존, 라우트, 및 태그.  a| 
테넌트 ID: 테넌트 ID입니다. Zone_name: Zone 이름. 오프셋: 결과 집합 수집을 시작하기 전에 건너뛸 항목 수입니다. 제한값: 반환할 항목 수입니다.



 a| 
"내려가세요
 a| 
"/v2.1/Tenants/{tenant_id}/" zones/{zone_name}/subnets/"{id}"
| 테넌트 및 존에 대해 생성된 특정 서브넷 객체의 세부 정보를 검색할 수 있습니다. VLAN, 서브테넌트, 존, 라우트, 입력한 ID를 기준으로 태그를 지정합니다.  a| 
테넌트 ID: 테넌트 ID입니다. Zone_name: Zone 이름. id: 서브넷의 ID.



 a| 
POST를 누릅니다
 a| 
"/v2.1/Tenants/{tenant_id}/" zones/{zone_name}/subnets"
| 특정 테넌트 및 영역에 대한 서브넷 객체를 생성할 수 있습니다. 요청 본문의 값을 추가하여 이름, VLAN, CIDR, 서브테넌트 ID와 같은 지정된 매개 변수를 사용하여 서브테넌트 객체를 생성합니다. 루트 및 태그.  a| 
테넌트 ID: 테넌트 ID입니다. Zone_name: Zone 이름. ""{"name":"string","vlan":"1000", "CIDR":"10.0.0.0/24", "subtenant_id":"5d2fb0fb4f47df00015274e3", "route":[{"destination":"10.0.0.0/24", "keyn", "metric", "10.0:" 1:", "keyn",", "metric" 1:"10.0:",",","" 1:"keyn",""", "keyn""""" 1:".



 a| 
POST를 누릅니다
 a| 
"/v2.1/Tenants/{tenant_id}/" zones/{zone_name}/subnets/"{id}/tags"
| 테넌트의 서브넷 개체에 대한 태그를 생성하거나 교체할 수 있습니다. 요청 본문의 "key:value pair" 형식으로 서브넷 오브젝트의 ID와 태그 값을 추가합니다.  a| 
테넌트 ID: 테넌트 ID입니다. Zone_name: Zone 이름. id: 백업 객체의 ID입니다. "{"key1":"<태그 1>","key2":"<태그 2>","keyn":"<태그 N>"}"

|===