---
sidebar: sidebar 
permalink: seapiref_storagegrid_instances.html 
keywords: netapp, keystone, storagegrid, instances, 
summary: Keystone StorageGRID 인스턴스 
---
= StorageGRID 인스턴스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 표에 나열된 방법을 사용하여 StorageGRID 인스턴스를 설정하고 관리하여 오브젝트 스토리지를 지원합니다.

|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/storagegridInstances' | StorageGRID 인스턴스를 검색합니다. 


| POST를 누릅니다 | '/v2.1/storagegridInstances' | 호스트 오브젝트 스토리지에 대한 새 StorageGRID 인스턴스를 생성합니다. 


| "내려가세요 | '/v2.1/storagegridinstances/{id}' | ID별로 StorageGRID 인스턴스를 조회한다. 


| 'Put' | '/v2.1/storagegridinstances/{id}' | StorageGRID 인스턴스를 업데이트합니다. 
|===


== StorageGRID 인스턴스 특성

다음 표에서는 StorageGRID 인스턴스 특성을 보여 줍니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | StorageGRID 인스턴스의 고유 식별자입니다. 


| 이름 | 문자열 | StorageGRID 인스턴스 이름입니다. 


| ADMIN_Rest_Uri입니다 | 문자열($Uri) | StorageGRID 관리 노드 엔드포인트 


| '3점' | 문자열($Uri) | StorageGRID 끝점. 예: [""https://[], "https://[] ] 


| GRID_USERNAME입니다 | 문자열 | StorageGRID 사용자 이름입니다. 


| grid_password | 문자열 | StorageGRID 암호. 


| 테넌트_사용자 이름 | 문자열 | StorageGRID 테넌트 사용자 이름입니다. 


| tenant_password | 문자열 | StorageGRID 테넌트 암호입니다. 


| 'Ssubscription_number' | 문자열 | Zuora 구독 번호입니다. 
|===


== StorageGRID 인스턴스를 검색합니다

다음 표에 나열된 방법을 사용하여 StorageGRID 인스턴스를 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/storagegridInstances' | StorageGRID 인스턴스를 검색합니다. | 없음 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e3ba2840271823644cb8ab6",
        "name": "NSE StorageGRID Dev1",
        "user_id": "5bbee380a2df7a04d43acaee",
        "admin_rest_uri": "https://sggmi-dev.dev.ausngs.netapp.au",
        "s3_endpoints": [
          "https://sgs3.dev.ausngs.netapp.au"
        ],
        "subscription_number": "A-S00004566"
      }
    ]
  }
}
....


== ID별로 StorageGRID 인스턴스를 검색합니다

다음 표에 나열된 방법을 사용하여 ID별로 StorageGRID 인스턴스를 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/storagegridinstances/{id}' | ID별로 StorageGRID 인스턴스를 조회한다. | id(string): StorageGRID 인스턴스의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e3ba2840271823644cb8ab6",
        "name": "NSE StorageGRID Dev1",
        "user_id": "5bbee380a2df7a04d43acaee",
        "admin_rest_uri": "https://sggmi-dev.dev.ausngs.netapp.au",
        "s3_endpoints": [
          "https://sgs3.dev.ausngs.netapp.au"
        ],
        "subscription_number": "A-S00004566"
      }
    ]
  }
}
....


== ID별로 StorageGRID 인스턴스를 만듭니다

다음 표에 나열된 방법을 사용하여 ID별로 StorageGRID 인스턴스를 만듭니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/storagegridinstances/{id}' | ID별로 StorageGRID 인스턴스를 조회한다. | id(string): StorageGRID 인스턴스의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
{
  "name": "Grid1",
  "admin_rest_uri": "https://examplegrid.com",
  "s3_endpoints": [
    "https://s3.examplegrid.com",
    "https://s3.location.company.com"
  ],
  "grid_username": "root",
  "grid_password": "string",
  "tenant_username": "root",
  "tenant_password": "string",
  "subscription_number": "A-S00003969"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "Grid1",
        "admin_rest_uri": "https://examplegrid.com",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "s3_endpoints": [
          "https://s3.examplegrid.com",
          "https://s3.location.company.com"
        ],
        "subscription_number": "A-S00003969"
      }
    ]
  }
}
....


== ID별로 StorageGRID 인스턴스를 수정합니다

다음 표에 나열된 방법을 사용하여 ID별로 StorageGRID 인스턴스를 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/storagegridinstances/{id}' | ID별로 StorageGRID 인스턴스를 수정합니다. | id(string): StorageGRID 인스턴스의 고유 식별자입니다. 
|===
필요한 요청 본문 속성: "없음"

* 요청 본문 예: *

....
{
  "name": "Grid1",
  "admin_rest_uri": "https://examplegrid.com",
  "s3_endpoints": [
    "https://s3.examplegrid.com",
    "https://s3.location.company.com"
  ],
  "grid_username": "root",
  "grid_password": "string",
  "tenant_username": "root",
  "tenant_password": "string",
  "subscription_number": "A-S00003969"
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "Grid1",
        "admin_rest_uri": "https://examplegrid.com",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "s3_endpoints": [
          "https://s3.examplegrid.com",
          "https://s3.location.company.com"
        ],
        "subscription_number": "A-S00003969"
      }
    ]
  }
}
....