---
sidebar: sidebar 
permalink: seapiref_block_storage_apis.html 
keywords: netapp, keystone, block storage, block stores, disks, host groups, initiators, apis 
summary: Keystone 블록 스토리지 API 
---
= 블록 스토리지 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
블록 스토리지 API를 사용하여 블록 스토리지를 보고 관리할 수 있습니다.

디스크를 생성하기 전에 블록 저장소를 만들어야 합니다. 디스크를 생성할 때 호스트 그룹을 생성하거나 디스크를 액세스할 기존 호스트 그룹을 선택해야 합니다. 자세한 내용은 을 참조하십시오 link:sewebiug_working_with_block_storage_overview.html["블록 스토리지 작업"].



== 블록 저장소

블록 저장소 API를 사용하여 블록 저장소를 검색하고 관리할 수 있습니다.

[cols="1,1,3,2"]
|===
| HTTP 동사 | 경로 | 설명 | 필수 매개 변수/요청 본문 


 a| 
"내려가세요
 a| 
'/v2.1/블록스토어'
| 모든 블록 저장소의 세부 정보를 검색할 수 있습니다. 블록 저장소 ID, IP 주소, 영역, 영역, 서브넷 ID, 및 태그.  a| 
오프셋: 결과 집합 수집을 시작하기 전에 건너뛸 항목 수입니다. 제한값: 반환할 항목 수입니다.



 a| 
"내려가세요
 a| 
'/v2.1/blockstore/{id}'
| 특정 블록 저장소의 세부 정보를 검색할 수 있습니다. 입력한 ID를 기준으로 IP 주소, 영역, 영역, 서브넷 ID, 태그 등의 블록 저장소의 세부 정보를 검색합니다.  a| 
ID: 블록 매장의 ID.



 a| 
POST를 누릅니다
 a| 
'/v2.1/블록스토어'
| 블록 저장소를 만들 수 있습니다. 서비스 프로토콜, 서브테넌트 ID, 영역, 서브넷 ID 및 태그와 같은 지정된 매개 변수를 사용하여 블록 저장소를 생성하려면 요청 본문의 값을 추가합니다.  a| 
'Subtenant_id': 서브테넌트의 ID. 존 : 존의 이름. Subnet_id: 서브넷의 ID.



 a| 
POST를 누릅니다
 a| 
`/v2.1/blockstore/{id}/''tags'
| 블록 저장소에 대한 태그를 만들거나 바꿀 수 있습니다. 블록 저장소의 ID와 태그의 값을 요청 본문의 "key:value pair" 형식으로 추가합니다.  a| 
ID: 블록 매장의 ID.



 a| 
'Put'
 a| 
'/v2.1/blockstore/{id}'
| ID를 기준으로 블록 저장소를 수정할 수 있습니다. 블록 저장소의 ID와 영역, 서비스 프로토콜 및 태그와 같은 요청 본문에서 수정할 값을 추가합니다.  a| 
ID: 블록 매장의 ID.



 a| 
"삭제"
 a| 
'/v2.1/blockstore/{id}'
 a| 
블록 저장소는 ID별로 삭제할 수 있습니다.
 a| 
ID: 블록 매장의 ID.

|===

NOTE: 블록 저장소를 삭제하기 전에 해당 저장소에 매핑된 모든 디스크를 삭제해야 합니다.



== 디스크

디스크 API를 사용하여 디스크를 검색하고 관리할 수 있습니다.

[cols="1,1,3,2"]
|===
| HTTP 동사 | 경로 | 설명 | 필수 매개 변수/요청 본문 


 a| 
"내려가세요
 a| 
'/v2.1/disks'
| 모든 디스크의 세부 정보를 검색할 수 있습니다. 블록 저장소 ID, 이름, 디스크 경로, 프로토콜, 스냅샷 정책 등의 디스크 세부 정보를 검색합니다. 및 태그.  a| 
오프셋: 결과 집합 수집을 시작하기 전에 건너뛸 항목 수입니다. 제한값: 반환할 항목 수입니다.



 a| 
"내려가세요
 a| 
'/v2.1/disks/{id}'
| 특정 디스크의 세부 정보를 검색할 수 있습니다. 블록 저장소 ID, 이름, 디스크 경로, 프로토콜, 스냅샷 정책 등의 디스크 세부 정보를 검색합니다. 입력한 ID를 기준으로 태그를 지정합니다.  a| 
id: 디스크의 ID입니다.



 a| 
POST를 누릅니다
 a| 
'/v2.1/disks'
| 디스크를 만들 수 있습니다. 요청 본문의 값을 추가하여 서브테넌트 ID, 영역, 이름, 디스크 경로, 스냅샷 정책 등과 같은 지정된 매개 변수를 사용하여 디스크를 생성합니다. 백업 정책 및 태그.  a| 
'Subtenant_id': 서브테넌트의 ID. 존 : 존의 이름. 이름: 디스크의 이름입니다. 디스크 경로. 프로토콜: 블록 디바이스 액세스에 사용되는 스토리지 프로토콜입니다. OS_TYPE: 호스트 운영체제의 종류이다. hostgroup_mappings: 호스트 그룹 매핑입니다. 'service_level': Standard, Premium, Premium-Tiering, Extreme 또는 Extreme-Tiering의 서비스 레벨 이름을 사용할 수 있습니다. size_gb: 디스크 크기(GB)입니다.



 a| 
POST를 누릅니다
 a| 
"/v2.1/disks/{id}/"스냅샷/{name}"
| 디스크의 스냅샷을 생성할 수 있습니다.  a| 
id: 디스크의 ID입니다. 이름: 스냅샷의 이름입니다.



 a| 
POST를 누릅니다
 a| 
'/v2.1/disks/{id}/''tags'
| 디스크에 대한 태그를 만들거나 바꿀 수 있습니다. 요청 본문의 "key:value pair" 형식으로 디스크의 ID와 태그 값을 추가합니다.  a| 
id: 디스크의 ID입니다.



 a| 
'Put'
 a| 
'/v2.1/disks/{id}'
| ID를 기준으로 디스크를 수정할 수 있습니다. 디스크의 ID와 이름, 서비스 수준, 스냅샷 정책, 백업 정책 및 태그와 같은 요청 본문에서 수정할 값을 추가합니다.  a| 
id: 디스크의 ID입니다. hostgroup_mappings: 호스트 그룹 매핑입니다.



 a| 
"삭제"
 a| 
'/v2.1/disks/{id}'
| ID를 기준으로 디스크를 삭제할 수 있습니다.  a| 
id: 디스크의 ID입니다.



 a| 
"삭제"
 a| 
"/v2.1/disks/{id}/"스냅샷/{name}"
| 디스크의 ID와 스냅샷 이름을 사용하여 디스크의 모든 스냅샷을 삭제할 수 있습니다.  a| 
id: 디스크의 ID입니다. 이름: 스냅샷의 이름입니다.

|===


== 호스트 그룹

디스크에 대한 액세스 제어는 호스트 그룹을 통해 관리됩니다. 호스트 그룹 API를 사용하여 호스트 그룹을 검색하고 관리할 수 있습니다.

[cols="1,1,3,2"]
|===
| HTTP 동사 | 경로 | 설명 | 필수 매개 변수/요청 본문 


 a| 
"내려가세요
 a| 
`/v2.1/hostgroups'
| 모든 호스트 그룹의 세부 정보를 검색할 수 있습니다. 이름, 서브테넌트 세부 정보, 테넌트 세부 정보, 존, 프로토콜, 이니시에이터, 호스트 그룹을 사용하는 디스크 및 태그  a| 
오프셋: 결과 집합 수집을 시작하기 전에 건너뛸 항목 수입니다. 제한값: 반환할 항목 수입니다.



 a| 
"내려가세요
 a| 
"/v2.1/hostgroups/{id}"
| 특정 호스트 그룹의 세부 정보를 검색할 수 있습니다. 이름, 서브테넌트 세부 정보, 테넌트 세부 정보, 존, 프로토콜, 이니시에이터, 호스트 그룹을 사용하는 디스크 및 입력한 ID를 기반으로 하는 태그.  a| 
id: 호스트 그룹의 ID입니다.



 a| 
POST를 누릅니다
 a| 
`/v2.1/hostgroups'
| 호스트 그룹을 생성할 수 있습니다. 요청 본문에 값을 추가하여 이름, 서브테넌트 ID, 영역, 프로토콜 등의 지정된 매개 변수를 사용하여 호스트 그룹을 생성합니다. 이니시에이터 및 태그  a| 
이름 : 호스트 그룹의 이름입니다. 'Subtenant_id': 서브테넌트의 ID. 존 : 존의 이름. 프로토콜: 블록 디바이스 액세스에 사용되는 스토리지 프로토콜입니다. OS_TYPE: 호스트 운영체제의 종류이다.



 a| 
POST를 누릅니다
 a| 
"/v2.1/hostgroups/{id}/""태그"
| 호스트 그룹에 대한 태그를 생성하거나 교체할 수 있습니다. 요청 본문의 "key:value pair" 형식으로 호스트 그룹의 ID와 태그 값을 추가합니다.  a| 
id: 호스트 그룹의 ID입니다.



 a| 
"삭제"
 a| 
"/v2.1/hostgroups/{id}"
| 호스트 그룹의 ID를 기준으로 모든 호스트 그룹을 삭제할 수 있습니다.  a| 
id: 호스트 그룹의 ID입니다.

|===


== 호스트 그룹의 이니시에이터입니다

호스트 그룹 API를 사용하여 호스트 그룹에 매핑된 이니시에이터를 검색하고 관리할 수 있습니다.

[cols="1,1,3,2"]
|===
| HTTP 동사 | 경로 | 설명 | 필수 매개 변수/요청 본문 


 a| 
"내려가세요
 a| 
"/v2.1/hostgroups/{id}/""이니시에이터"
| 모든 이니시에이터의 세부 정보를 검색할 수 있습니다. 이니시에이터 및 별칭을 검색합니다.  a| 
id: 호스트 그룹의 ID입니다.



 a| 
"내려가세요
 a| 
"/v2.1/hostgroups/{id}/""initiators/{alias}"
| 특정 이니시에이터의 세부 정보를 검색할 수 있습니다. 입력한 ID와 별칭을 기반으로 이니시에이터를 검색합니다.  a| 
id: 호스트 그룹의 ID입니다. 별칭: 초기자의 별칭 이름입니다.



 a| 
POST를 누릅니다
 a| 
"/v2.1/hostgroups/{id}/""이니시에이터"
 a| 
호스트 그룹의 이니시에이터를 생성할 수 있습니다. 요청 본문에 이니시에이터 및 해당 별칭의 값을 추가하여 호스트 그룹의 이니시에이터를 생성합니다.
 a| 
id: 호스트 그룹의 ID입니다. 별칭: 초기자의 별칭 이름입니다. "이니시에이터": 이니시에이터(iSCSI 정규화된 이름 또는 FC WWPN).



 a| 
패치
 a| 
"/v2.1/hostgroups/{id}/""initiators/{alias}"
| 이니시에이터를 수정할 수 있습니다. 요청 본문에 새 이니시에이터를 추가합니다.  a| 
id: 호스트 그룹의 ID입니다. 별칭: 초기자의 별칭 이름입니다. "이니시에이터": 이니시에이터(iSCSI 정규화된 이름 또는 FC WWPN)



 a| 
"삭제"
 a| 
"/v2.1/hostgroups/{id}/""initiators/{alias}"
 a| 
호스트 그룹의 ID와 이니시에이터의 별칭으로 이니시에이터를 삭제할 수 있습니다.
 a| 
id: 호스트 그룹의 ID입니다. 별칭: 초기자의 별칭 이름입니다.

|===
[NOTE]
====
호스트 그룹에 이니시에이터를 추가할 때 이니시에이터는 호스트 그룹 프로토콜과 일치해야 합니다. iSCSI 프로토콜을 사용하는 호스트 그룹에 IQN을 사용하고 FC 프로토콜을 사용하는 호스트 그룹에 WWPN을 사용해야 합니다.

호스트 그룹에서 이니시에이터를 삭제하면 호스트 그룹이 매핑될 모든 디스크에 영향을 미칩니다.

====