---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Keystone 서비스 레벨 
---
= 서비스 레벨
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 표에 나열된 방법을 사용하여 서비스 수준을 검색, 생성, 수정 및 삭제할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/서비스 수준' | 모든 서비스 수준을 검색합니다. 


| "내려가세요 | '/v2.1/serviceels/{id}' | ID별로 서비스 레벨을 조회한다. 


| POST를 누릅니다 | '/v2.1/서비스 수준' | 새 서비스 레벨을 생성합니다. 


| 'Put' | '/v2.1/serviceels/{id}' | ID별로 서비스 수준 세부 정보를 수정합니다. 


| "삭제" | '/v2.1/serviceels/{id}' | 서비스 레벨을 삭제합니다. 
|===


=== 서비스 수준 특성

다음 표에서는 서비스 수준 특성을 보여 줍니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 서비스 수준에 대한 고유 식별자입니다. 


| 이름 | 문자열 | 서비스 수준 이름입니다. 


| 설명 | 문자열 | 서비스 수준에 대한 설명입니다. 


| policy_name입니다 | 문자열 | 서비스 수준 서비스 품질(QoS) 이름 허용되는 값: nse_value, nse_standard, nse_performance 및 nse_extreme. 


| "사용 가능" | 부울 | 서비스 수준을 사용할 수 있는지 여부를 나타냅니다. 


| "조모했습니다. | 부울 | 서비스 수준이 폐기되었는지 여부를 나타냅니다. 


| 'peak_IOPS_per_TB' | 정수 | 해당 데이터의 최대 IOPS/TiB 


| 'expected_IOPS_per_TB' | 정수 | TiB당 최소 예상 IOPS 


| 절대_최소_IOPS | 정수 | 예상 IOPS가 이 값보다 작을 때 재정의로 사용되는 절대 최소 IOPS입니다. 


| 'peak_IOPS_allocation'을 선택합니다 | 문자열 | 최대 IOPS 할당. 허용되는 값: allocated_space 및 used_space 


| 'IO_BLOCK_SIZE_KB | 정수 | 입출력 블록 크기(KiB) 


| min_size_gb | 정수 | 최소 크기(GiB) 


| max_size_GB'입니다 | 정수 | 최대 크기(GiB) 


| max_peak_IOPS | 정수 | 서비스 수준에 대한 최대 피크 IOPS입니다. 


| max_expected_IOPS | 정수 | 예상되는 최대 IOPS 


| '자동 확장_최대_퍼센트' | 정수 | 최대 자동 확장 비율. 


| 'ontap_aggregate' | –  a| 
ONTAP 애그리게이트 목록입니다. ONTAP 애그리게이트는 다음과 같이 구성됩니다.

* 'cluster_UIID:ONTAP 클러스터 UUID
* 'aggr_name:ONTAP 집계 이름'
* ''aggr_uuid:ONTAP 집계 UUID'
* 'node_name:ONTAP cluster node name' 예:


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| 'primary_volume_defaults'입니다 | –  a| 
* snapshot_auto_delete_target_free_space(정수): 이 옵션은 스냅샷 복사본의 자동 삭제를 중지해야 하는 여유 공간 비율을 지정합니다.
* Auto_size_mode(string): 볼륨의 자동 크기 조정 모드입니다. 허용되는 값: off, grow, grow_shrink 예:


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


=== 서비스 수준 검색

다음 표에 나열된 방법을 사용하여 모든 서비스 수준을 검색할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/서비스 수준' | 모든 서비스 수준을 검색합니다. | 없음 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== 이름별로 서비스 레벨을 검색합니다

다음 표에 나열된 방법을 사용하여 이름별로 서비스 수준을 검색할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/serviceels/{name}' | 이름별로 서비스 레벨을 조회한다. | 이름(string): 서비스 수준 이름입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


=== 서비스 레벨을 생성합니다

다음 표에 나열된 방법을 사용하여 서비스 수준을 만듭니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/서비스 수준' | 서비스 레벨을 생성합니다. | 없음 
|===
요청 본문 속성: name, policy_name

* 요청 본문 예: *

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


=== 서비스 수준을 수정합니다

다음 표에 나열된 방법을 사용하여 서비스 수준을 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/serviceels/{name}' | 서비스 수준의 세부 정보를 수정합니다. | 이름(string): 서비스 수준 이름입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
* 응답 바디 예: *

....
TBA
....


=== ID별로 서비스 수준을 삭제합니다

다음 표에 나열된 방법을 사용하여 ID별로 서비스 수준을 삭제합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | '/v2.1/serviceels/{name}' | ID로 식별된 서비스 레벨을 삭제합니다. | 이름(string): 서비스 수준 이름입니다. 
|===
* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
No content for succesful delete
....