---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Keystone 서비스 요청 
---
= 서비스 요청
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 표에 나열된 메소드를 사용하여 서비스 요청을 생성하고 검색합니다.

|===


| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/Tenants/{tenant_id}/service필수' | 서비스 요청을 검색합니다. 


| "내려가세요 | '/v2.1/Tenants/{tenant_id}/service필수 조건/{id}' | ID별 서비스 요청 조회 


| POST를 누릅니다 | '/v2.1/Tenants/{tenant_id}/service필수 요소/' | 서비스 요청을 생성합니다. 


| "내려가세요 | '/v2.1/Tenants/{tenant_id}/서비스 필수/범주' | 서비스 요청 범주를 검색합니다. 
|===


== 서비스 요청 속성

다음 표에서는 서비스 요청 특성을 보여 줍니다.

|===


| 속성 | 유형 | 설명 


| 아이디 | 문자열 | 서비스 요청의 식별자입니다. 예: 'RQ0035952014. 


| '제목' | 문자열 | 서비스 요청의 제목입니다. 


| '코멘트' | 문자열 | 서비스 요청에 대한 설명입니다 


| '카테고리'입니다 | 문자열 | 요청의 범주: 백업, 재해 복구, 기술, 기타 또는 구독 


| 우선 순위 | 문자열 | 서비스 요청의 우선 순위: 매우 낮음, 낮음, 보통, 높음 또는 긴급 


| '비문' | 문자열 | Zuora 구독 번호입니다. 


| '약속' | –  a| 
구독 약정 세부 정보:

* 서비스 수준(문자열): 서비스 수준: 표준, 프리미엄 또는 익스트림.
* new_p확약(정수): 새 총 용량이 필요합니다.




| 존 | 문자열 | 영역 이름입니다. 


| 'Subtenant_id'입니다 | 문자열 | 서브테넌트 식별자입니다. 


| 'STORAGE_OBJECT_TYPE' | 문자열 | 스토리지 오브젝트 유형: 파일 서버 또는 블록 저장소 


| 'STORAGE_OBJECT_ID'입니다 | 문자열 | 스토리지 객체의 식별자입니다. 예: '5d2fb0fb4f47df00015274e3' 


| 'service_type | 문자열 | 서비스 유형: 파일 서비스, 블록 스토리지 또는 오브젝트 스토리지 
|===


== 서비스 요청을 검색합니다

다음 표에 나열된 방법을 사용하여 지정된 테넌트에 대한 서비스 요청 범주를 검색합니다.

|===


| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요. | '/v2.1/Tenants/{tenant_id}/service필수' | 서비스 요청을 검색합니다. | 'tenant_id': (선택 사항) 지정된 테넌트에 대한 서비스 요청을 반환합니다. '오프셋'과 '한계'는 를 참조하십시오 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== ID별 서비스 요청 조회

다음 표에 나열된 방법을 사용하여 서비스 요청 ID별로 서비스 요청을 검색합니다.

|===


| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/Tenants/{tenant_id}/service필수 조건/{id}' | ID별 서비스 요청 조회  a| 
* Tenant_id: Tenant ID
* "id": 서비스 요청 IDFor 예: SRQ0035952014


|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== 서비스 요청을 생성합니다

다음 표에 나열된 방법을 사용하여 서비스 요청을 만듭니다.

|===


| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/Tenants/{tenant_id}/서비스 필수/범주' | 서비스 요청을 생성합니다. | `tenant_id`: 테넌트 식별자입니다. 
|===
필요한 요청 본문 속성: 필요한 속성은 서비스 요청 범주에 따라 달라집니다. 다음 표에서는 요청 본문 특성을 보여 줍니다.

|===


| 범주 | 필수 요소입니다 


| 구독 | `subscription` 및 `commitment` 


| 재해 복구 | `storage_object_type`, `subtenant_id`, 및 `storage_object_id` 


| 기술 | `subtenant_id` 및 `service_type`If(경우 `service_type` 파일 서비스 또는 블록 스토리지인지 확인하십시오. 영역이 필요합니다. 


| 기타 | Zone(영역) 
|===
* 요청 본문 예: *

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


== 서비스 요청 범주를 검색합니다

다음 표에는 지정된 테넌트에 대한 검색 서비스 요청 범주가 나와 있습니다.

|===


| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/Tenants/{tenant_id}/서비스 필수/범주' | 서비스 요청 범주를 검색합니다. | `tenant_id:` (선택 사항) 지정된 테넌트에 대한 서비스 요청을 반환합니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....