---
sidebar: sidebar 
permalink: seapiref_file_services_apis.html 
keywords: netapp, keystone, file services, file servers, file shares, apis 
summary: Keystone 파일 서비스 API 
---
= 파일 서비스 API
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
파일 서비스 API를 사용하여 파일 서버 및 파일 공유를 보고 관리할 수 있습니다.

파일 공유를 생성하기 전에 파일 서버를 생성하여 호스팅해야 합니다.



== 파일 서버 API

파일 서버 API를 사용하여 파일 서버를 보고 관리할 수 있습니다. 파일 서버에 대한 자세한 내용은 을 참조하십시오 link:hsewebiug_create_a_file_server.html["파일 서버를 생성합니다"].

[cols="1,1,3,2"]
|===
| HTTP 동사 | 경로 | 설명 | 필수 매개 변수/요청 본문 


 a| 
"내려가세요
 a| 
'/v2.1/파일 서버'
| 모든 파일 서버의 세부 정보를 검색할 수 있습니다. 파일 서버 ID, 이름, 영역, 영역, 테넌트, 테넌트 등과 같은 파일 서버의 세부 정보를 검색합니다. 및 태그.  a| 
오프셋: 결과 집합 수집을 시작하기 전에 건너뛸 항목 수입니다. 제한값: 반환할 항목 수입니다.



 a| 
"내려가세요
 a| 
'/v2.1/fileserver/{id}'
| 특정 파일 서버의 세부 정보를 검색할 수 있습니다. 이름, 영역, 영역, 테넌트, 테넌트 등의 파일 서버 세부 정보를 검색합니다. 입력한 ID를 기준으로 태그를 지정합니다.  a| 
id: 파일 서버의 ID입니다.



 a| 
POST를 누릅니다
 a| 
'/v2.1/파일 서버'
| 파일 서버를 생성할 수 있습니다. 요청 본문의 값을 추가하여 이름, 서브테넌트 ID, 영역, 서브넷 ID와 같은 지정된 매개 변수를 사용하여 파일 서버를 생성합니다.  a| 
이름 : 파일 서버의 이름입니다. 'Subtenant_id': 서브테넌트의 ID. 존 : 존의 이름. Subnet_id: 서브넷의 ID.



 a| 
POST를 누릅니다
 a| 
'/v2.1/fileserver/{id}/''tags'
| 파일 서버에 대한 태그를 만들거나 바꿀 수 있습니다. 요청 본문의 "key:value pair" 형식으로 파일 서버의 ID와 태그 값을 추가합니다.  a| 
id: 파일 서버의 ID입니다.



 a| 
'Put'
 a| 
'/v2.1/fileserver/{id}'
| ID를 기준으로 파일 서버를 수정할 수 있습니다. 파일 서버의 ID와 이름, 프로토콜, 영역, 영역 및 태그와 같이 요청 본문에서 수정할 값을 추가합니다.  a| 
id: 파일 서버의 ID입니다.



 a| 
"삭제"
 a| 
'/v2.1/fileserver/{id}'
 a| 
파일 서버의 ID를 기준으로 삭제할 수 있습니다.
 a| 
id: 파일 서버의 ID입니다.

|===
[NOTE]
====
파일 서버를 삭제하기 전에 해당 서버에 매핑된 모든 파일 공유를 삭제해야 합니다.

CIFS 지원 파일 서버를 삭제한 후 Active Directory 컴퓨터 개체는 그대로 유지됩니다. Active Directory 관리자에게 문의하여 삭제된 파일 서버의 컴퓨터 개체를 Active Directory에서 수동으로 제거합니다.

====


== 파일 공유 API

파일 공유 API를 사용하여 파일 공유를 보고 관리할 수 있습니다. 파일 공유에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_create_a_new_file_share.html["파일 공유를 생성합니다"].

[cols="1,1,3,2"]
|===
| HTTP 동사 | 경로 | 설명 | 필수 매개 변수/요청 본문 


 a| 
"내려가세요
 a| 
'/v2.1/fileshaes'
| 모든 파일 공유의 세부 정보를 검색할 수 있습니다. ID, 이름, 스냅샷 정책, 프로토콜 등의 파일 공유에 대한 세부 정보를 검색합니다. 파일 서버 IP 및 태그.  a| 
오프셋: 결과 집합 수집을 시작하기 전에 건너뛸 항목 수입니다. 제한값: 반환할 항목 수입니다.



 a| 
"내려가세요
 a| 
'/v2.1/fileshaes/{id}'
| 특정 파일 공유의 세부 정보를 검색할 수 있습니다. ID, 이름, 스냅샷 정책, 프로토콜, 파일 서버 IP 등의 파일 공유의 세부 정보를 검색합니다. 입력한 ID를 기준으로 태그를 지정합니다.  a| 
id: 파일 공유의 ID입니다.



 a| 
POST를 누릅니다
 a| 
'/v2.1/fileshaes'
| 파일 공유를 생성할 수 있습니다. ID, 이름, 스냅샷 정책, 프로토콜 등의 지정된 매개 변수를 사용하여 파일 공유를 생성하려면 요청 본문의 값을 추가합니다. 파일 서버 IP 및 태그.  a| 
이름 : 파일 공유의 이름입니다. '공유_경로': 파일 공유의 경로입니다. 'fileserver_id': 파일 서버의 ID. size_gb: GB의 파일 공유 크기입니다. 'service_level': Standard, Premium, Premium-Tiering, Extreme 또는 Extreme-Tiering의 서비스 레벨 이름을 사용할 수 있습니다. '프로토콜': 파일 공유(NFS, CIFS 또는 멀티 프로토콜)를 액세스하는 데 사용되는 프로토콜입니다. 보안 스타일(Unix 또는 NTFS). Export_policy: 파일 공유의 내보내기 정책입니다.



 a| 
POST를 누릅니다
 a| 
'/v2.1/fileshaes/{id}/'s napshot/{name}'
| 파일 공유의 스냅샷을 생성할 수 있습니다.  a| 
id: 파일 공유의 ID입니다. 이름: 스냅샷의 이름입니다.



 a| 
POST를 누릅니다
 a| 
'/v2.1/fileshaes/{id}/''tags'
| 파일 공유에 대한 태그를 만들거나 바꿀 수 있습니다. 요청 본문의 "key:value pair" 형식으로 파일 공유의 ID와 태그 값을 추가합니다.  a| 
id: 파일 공유의 ID입니다.



 a| 
'Put'
 a| 
'/v2.1/fileshaes/{id}'
| ID를 기준으로 모든 파일 공유를 수정할 수 있습니다. 파일 서버의 ID와 이름, 프로토콜, 스냅샷 정책, 백업 정책, 태그 등 요청 본문에서 수정할 값을 추가합니다.  a| 
id: 파일 공유의 ID입니다. 이름 : 파일 공유의 이름입니다. size_gb: GB의 파일 공유 크기입니다. 'service_level': Standard, Premium, Premium-Tiering, Extreme 또는 Extreme-Tiering의 서비스 레벨 이름을 사용할 수 있습니다. '프로토콜': 파일 공유(NFS, CIFS 또는 멀티 프로토콜)를 액세스하는 데 사용되는 프로토콜입니다. Export_policy: 파일 공유의 내보내기 정책입니다.



 a| 
"삭제"
 a| 
'/v2.1/fileshaes/{id}'
| ID로 모든 파일 공유를 삭제할 수 있습니다.  a| 
id: 파일 공유의 ID입니다.



 a| 
"삭제"
 a| 
'/v2.1/fileshaes/{id}/'s napshot/{name}'
| 파일 공유의 ID와 스냅샷의 이름으로 파일 공유의 모든 스냅샷을 삭제할 수 있습니다.  a| 
id: 파일 공유의 ID입니다. 이름: 스냅샷의 이름입니다.

|===

NOTE: CIFS 공유의 경우 공유 경로 끝에 '$' 문자를 추가하면 hidomyhidendshare$ 등의 숨겨진 공유가 됩니다.
