---
sidebar: sidebar 
permalink: seapiref_zones.html 
keywords: netapp, keystone, zones, 
summary: 키스톤 영역 
---
= 존
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 표에 나열된 방법을 사용하여 영역을 생성, 수정 및 삭제할 수 있습니다. 영역을 검색할 수 있는 API는 (Consumer) Administration API를 참조하십시오.

|===
| HTTP 메서드 | 경로 | 설명 


| POST를 누릅니다 | '/v2.1/Zones' | 새 영역을 만듭니다. 


| 'Put' | '/v2.1/zones/{name}' | 영역의 세부 정보를 수정합니다. 


| "삭제" | '/v2.1/zones/{name}' | 영역을 삭제합니다. 
|===


=== 영역 속성

다음 표에서는 영역 특성을 보여 줍니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 영역의 고유 식별자입니다. 


| 이름 | 문자열 | 영역 이름입니다. 


| 설명 | 문자열 | 영역에 대한 설명입니다. 


| REGion_NAME'입니다 | 문자열 | 영역이 있는 영역의 이름입니다. 
|===


=== 모든 Zone을 조회한다

다음 표에 나열된 방법을 사용하여 모든 영역 또는 영역의 하위 집합을 검색할 수 있습니다. 영역을 지정하면 해당 테넌트에 속한 블록 저장소만 반환됩니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/Zones' | 영역 검색. | (선택 사항) 지역 이름(string) "offset" 및 "limit"(참조 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 2,
    "limit": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
....


=== 이름으로 Zone을 조회한다

다음 표에 나열된 방법을 사용하여 영역 이름으로 영역을 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/zones/{name}' | 이름으로 Zone을 조회한다. | 이름(문자열): 영역 이름 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ce5d919b68d3b82dc34bef2",
        "name": "au-west1-a",
        "description": "au-west1-a",
        "region": "au-west1"
      }
    ]
  }
}
....


=== 영역을 만듭니다

다음 표에 나열된 방법을 사용하여 영역을 만듭니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/Zones' | 영역 내에 새 영역을 만듭니다. | 없음 
|===
요청 본문 속성: 이름, 설명, REGION_NAME

* 요청 본문 예: *

....
{
  "name": "MyZoneName",
  "description": "DescriptionOfMyZone",
  "region_name": "MyRegionName"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "DescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


=== 영역을 수정합니다

영역을 수정하려면 다음 표에 나열된 방법을 사용합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/zones{name}' | 이름으로 식별된 영역을 수정합니다. | 이름(string) : 영역의 이름입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
{
  "name": "MyZoneName",
  "description": "NewDescriptionOfMyZone"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61741c9b64790001fe9663",
        "name": "MyZoneName",
        "description": "NewDescriptionOfMyZone",
        "region": "MyRegionName"
      }
    ]
  }
}
....


=== 영역을 삭제합니다

영역을 삭제하려면 다음 표에 나열된 방법을 사용합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | '/v2.1/zones{name}' | 이름으로 식별되는 단일 영역을 삭제합니다. 영역 내의 모든 스토리지 리소스를 먼저 삭제해야 합니다. | 이름(string) : 영역의 이름입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

성공적으로 삭제해도 반환할 콘텐츠가 없습니다.
