---
sidebar: sidebar 
permalink: seapiref_ontap_clusters.html 
keywords:  
summary:  
---
= ONTAP 클러스터
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
다음 표에 나열된 방법을 사용하여 ONTAP 클러스터를 검색, 생성, 수정 및 삭제할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/ontapcluster' | 모든 ONTAP 클러스터를 검색합니다. 


| "내려가세요 | "/v2.1/ontapcluster/{id}" | ID별로 ONTAP 클러스터를 검색합니다. 


| POST를 누릅니다 | '/v2.1/ontapcluster' | 새 ONTAP 클러스터를 생성합니다. 


| 'Put' | "/v2.1/ontapcluster/{id}" | ID별로 ONTAP 클러스터 인벤토리를 업데이트합니다. 


| "삭제" | "/v2.1/ontapcluster/{id}" | ONTAP 클러스터를 삭제합니다. 
|===


== ONTAP 클러스터 특성

다음 표에는 ONTAP 클러스터 특성이 나와 있습니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | ONTAP 클러스터의 고유 식별자입니다. 


| 이름 | 문자열 | ONTAP 클러스터 이름입니다. 


| 우UID | 문자열 | ONTAP 클러스터 UUID(범용 고유 식별자) 


| 'Management_IP'입니다 | 문자열 | ONTAP 클러스터 관리 IPv4 주소입니다. 


| '사용자 이름' | 문자열 | ONTAP 클러스터 이름입니다 


| "암호" | 문자열 | ONTAP 클러스터 암호입니다 


| 'provisioning_state'입니다 | 문자열  a| 
클러스터를 프로비저닝 작업에 사용할 수 있는지 여부를 식별합니다. 옵션은 다음과 같습니다.

* 개방형
* 종료됨




| Data_network_ip_CIDR | 문자열 | 서브넷의 CIDR 표시입니다. 


| Data_network_default_gateway | 문자열 | IPv4 주소입니다. 


| data_network_ports를 선택합니다 | –  a| 
ONTAP 클러스터 데이터 네트워크 포트 목록

[listing]
----
For example:
[
  {
  "node_name": "dev-ots-per01-01",
  "port_name": "e0c-120",
  "parent_port": "e0c"
  }
]
----


| '인터클러스터_생명수' | –  a| 
ONTAP 클러스터 인터클러스터 LIF.

[listing]
----
For example:
[
  {
  "name": "peer1",
  "node": "aff-01",
  "port": "a0a-103",
  "address": "10.128.113.232",
  "netmask": "255.255.255.0"
  },
{
  "name": "peer2",
  "node": "aff-02",
  "port": "a0a-103",
  "address": "10.128.113.233",
  "netmask": "255.255.255.0"
  }
]
----


| 'sVM_root_service_level'입니다 | 문자열 | ONTAP 클러스터 스토리지 가상 시스템(SVM) 루트 서비스 수준 이름입니다. 적용 가능한 값은 Standard(표준), Extreme(익스트림) 또는 Premium(프리미엄)입니다. 이 서비스 수준은 기본적으로 클러스터에서 생성된 모든 SVM에 할당됩니다. 클러스터는 앞서 언급한 서비스 수준과 연결된 집계가 있어야 합니다. 


| 존 | 문자열 | 영역 이름입니다. 


| 'Ssubscription_number' | 문자열 | Zuora 구독. 


| '서비스_사용 가능' | –  a| 
사용 가능한 서비스 및 해당 상태 목록 예를 들면 다음과 같습니다.

[listing]
----
{
  "fcp": false,
  "iscsi": true,
  "nas": true
  }
----


| data_fcp_ports를 선택합니다 | –  a| 
FCP 지원 ONTAP 클러스터의 노드 및 포트 목록 예를 들면 다음과 같습니다.

[listing]
----
[  {   "node_name": "aff-01",   "port_name": "0g"  },  {   "node_name": "aff-01",   "port_name": "0h"
  ]
----


| is_MCC(is_MCC) | 부울 | 클러스터가 MetroCluster를 사용하는지 여부를 나타냅니다. 기본값은 False입니다. 


| mcc_partner_cluster'입니다 | 문자열 | MetroCluster 쌍에 있는 현재 클러스터의 파트너 클러스터의 식별자입니다. MetroCluster에 대해 클러스터가 설정된 경우 필요합니다. 
|===


== 모든 ONTAP 클러스터를 검색합니다

모든 ONTAP 클러스터 또는 ONTAP 클러스터의 하위 집합을 검색하려면 다음 방법을 사용하십시오.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/ontapcluster' | 모든 ONTAP 클러스터를 검색합니다. | '오프셋'과 '한계'는 를 참조하십시오 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 2,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": []
      },
      {
        "id": "5eaf5249f038943eb46b6608",
        "name": "aff",
        "region": "au-east1",
        "zone": "au-east1-b",
        "uuid": "62d649d2-07a1-11e6-9549-00a0985c0dcb",
        "management_ip": "10.128.113.69",
        "username": "admin",
        "services_available": {
          "fcp": true,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "aff-01",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          },
          {
            "node_name": "aff-02",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          }
        ],
        "data_network_ip_cidr": "10.50.50.0/24",
        "data_network_default_gateway": "10.50.50.1",
        "svm_root_service_level": "premium",
        "intercluster_lifs": [
          {
            "name": "peer1",
            "node": "aff-01",
            "port": "a0a-103",
            "address": "10.128.113.232",
            "netmask": "255.255.255.0"
          },
          {
            "name": "peer2",
            "node": "aff-02",
            "port": "a0a-103",
            "address": "10.128.113.233",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00004635",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [
          {
            "node_name": "aff-01",
            "port_name": "0g"
          },
          {
            "node_name": "aff-01",
            "port_name": "0h"
          },
          {
            "node_name": "aff-02",
            "port_name": "0g"
          },
          {
            "node_name": "aff-02",
            "port_name": "0h"
          }
        ],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


== ID별로 ONTAP 클러스터를 검색합니다

ID별로 ONTAP 클러스터를 검색하려면 다음 방법을 사용하십시오.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | "/v2.1/ontapcluster/{id}" | ID로 식별된 ONTAP 클러스터를 검색합니다. | id(string): ONTAP 클러스터의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


== ONTAP 클러스터를 생성합니다

다음 표의 API를 사용하여 ONTAP 클러스터를 생성합니다.

ONTAP 클러스터는 항상 iSCSI 서비스가 활성화된 상태로 생성됩니다. 필요한 경우 인프라가 지원하는 경우 FCP 서비스를 활성화할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/ontapcluster' | ONTAP 클러스터를 생성합니다. | 없음 
|===
필수 요청 본문 속성: name, uuuid, management_ip, username, password data_network_ip_cIDR, data_network_default_gateway, 인터클러스터_lifs, 영역

FCP가 활성화된 경우('services_available' FCP 속성 사용) data_fcp_ports가 필요합니다.

is_MCC가 사실이라면 mcc_partner_cluster가 필요합니다.

* 요청 본문 예: *

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "clustername-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "clustername-01-icl01",
      "node": "clustername-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "extreme",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": true
  },
  "data_fcp_ports": [
  ],
  "is_mcc": false,
}
....
* 응답 바디 예: *

....
{
    "status": {
        "user_message": "Okay. New resource created.",
        "verbose_message": "",
        "code": 201
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "clustername-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "extreme",
                "intercluster_lifs": [
                    {
                        "name": "clustername-01-icl01",
                        "node": "clustername-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


== ONTAP 클러스터를 수정합니다

다음 목록에 나와 있는 방법을 사용하여 ONTAP 클러스터를 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | "/v2.1/ontapcluster/{id}" | ID로 식별되는 ONTAP 클러스터의 세부 정보를 수정합니다. | id(string): ONTAP 클러스터의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "dev-ots-syd01-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "dev-ots-syd01-01-icl01",
      "node": "dev-ots-syd01-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "standard",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": false
  },
  "data_fcp_ports": [
  ]
}
....
* 응답 바디 예: *

....
{
    "status": {
        "user_message": "Okay. Accepted for processing.",
        "verbose_message": "",
        "code": 202
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "dev-ots-syd01-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "standard",
                "intercluster_lifs": [
                    {
                        "name": "dev-ots-syd01-01-icl01",
                        "node": "dev-ots-syd01-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


== ONTAP 클러스터를 삭제합니다

다음 표에 나와 있는 방법을 사용하여 ONTAP 클러스터를 삭제합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | "/v2.1/ontapcluster/{id}" | ID로 식별되는 ONTAP 클러스터를 삭제합니다. | id(string): ONTAP 클러스터의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
No content for succesful delete
....