---
sidebar: sidebar 
permalink: seapiref_object_storage_apis.html 
keywords: netapp, keystone, object, storage, apis, 
summary: Keystone 오브젝트 스토리지 API 
---
= 오브젝트 스토리지 API
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 섹션에서는 오브젝트 스토리지, 오브젝트 스토리지 사용자, 오브젝트 스토리지 그룹을 관리하는 API를 제공합니다.

오브젝트 스토리지 워크플로우에는 다음 작업이 포함됩니다.

* 오브젝트 스토리지 계정을 생성합니다.
* 오브젝트 스토리지 그룹을 생성합니다.
* 오브젝트 스토리지 사용자를 생성합니다.
* 사용자의 S3 키를 생성합니다.




=== 오브젝트 스토리지 그룹

다음 표에 나열된 방법을 사용하여 오브젝트 스토리지 그룹을 검색, 생성 또는 수정할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/objectiam/groups' | 오브젝트 스토리지 그룹을 검색합니다. 


| "내려가세요 | '/v2.1/objectiam/groups/{id}' | ID별로 오브젝트 스토리지 그룹을 검색합니다. 


| POST를 누릅니다 | '/v2.1/objectiam/groups' | 오브젝트 스토리지 ID 액세스 관리 그룹을 생성합니다. 


| 'Put' | '/v2.1/objectiam/groups/{id}' | ID로 식별되는 오브젝트 스토리지 그룹을 수정합니다. 


| "삭제" | '/v2.1/objectiam/groups/{id}' | ID로 식별되는 오브젝트 스토리지 그룹을 삭제합니다. 
|===


==== 오브젝트 스토리지 그룹 특성

다음 표에서는 오브젝트 스토리지 특성을 보여 줍니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 오브젝트 스토리지 그룹의 고유 식별자입니다. 


| 이름 | 문자열 | 오브젝트 스토리지 그룹 이름입니다. 


| '소방' | 문자열 | 그룹이 속한 서브테넌트의 이름입니다. 


| 'Subtenant_id'입니다 | 문자열 | 그룹이 속한 하위 테넌트의 식별자입니다. 


| '소작인' | 문자열 | 그룹이 속한 테넌트의 이름입니다. 


| 테넌트_id | 문자열 | 그룹이 속한 테넌트의 식별자입니다. 


| 3정책 |   a| 
S3 정책 예:

[listing]
----
"s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
----
|===


=== 오브젝트 스토리지 그룹을 검색합니다

다음 표에 나열된 방법을 사용하여 모든 오브젝트 스토리지 그룹 또는 오브젝트 스토리지 그룹의 하위 집합을 검색할 수 있습니다. 'subtenant_id'를 지정하면 해당 서브테넌트에 속한 객체 스토리지 그룹만 반환됩니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectiam/groups' | 모든 오브젝트 스토리지 그룹을 검색합니다. 필요에 따라 서브테넌트 ID를 지정하여 서브테넌트와 연결된 객체 스토리지 그룹만 검색합니다. | 'Subtenant_id(string)': IAM(Identity and Access Management) 사용자/그룹과 연결된 서브테넌트 ID입니다. '오프셋'과 '한계'는 를 참조하십시오 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]

....


==== ID별로 오브젝트 스토리지 그룹을 검색합니다

다음 표에 나열된 방법을 사용하여 ID별로 개체 스토리지 그룹을 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectiam/groups/{id}' | ID별로 오브젝트 스토리지 그룹을 검색합니다. | "id(string)": 객체 스토리지 그룹의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


==== 오브젝트 스토리지 그룹을 생성합니다

개체 스토리지 그룹을 생성하려면 다음 방법에 나열된 방법을 사용합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/objectiam/groups/' | 오브젝트 스토리지 사용자를 호스팅하기 위한 새 오브젝트 스토리지 그룹 서비스를 생성합니다. | 없음 
|===
요청 본문 속성: name, subtenant_id, s3Policy

* 요청 본문 예: *

....
{
  "name": "MyNewGroup",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fa312c356a0001a73841",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T07:05:21.130260774Z",
        "updated": "2020-06-02T07:05:21.130260774Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== 오브젝트 스토리지 그룹을 수정합니다

다음 표에 나열된 방법을 사용하여 오브젝트 스토리지 그룹을 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/objectiam/groups/{id}' | 오브젝트 스토리지 그룹을 수정합니다. | "id(string)": 객체 스토리지 그룹의 고유 식별자입니다. 
|===
요청 본문 속성: name, subtenant_id, s3Policy

* 요청 본문 예: *

....
{
  "s3_policy": {
    "Statement": [
        {
        "Action": [
            "s3:ListAllMyBuckets",
            "s3:ListBucket",
            "s3:ListBucketVersions",
            "s3:GetObject",
            "s3:GetObjectTagging",
            "s3:GetObjectVersion",
            "s3:GetObjectVersionTagging"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:s3:::*"
        }
    ]
  }
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fe822c356a0001a73859",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:23:46.43550235Z",
        "updated": "2020-06-02T07:23:46.43550235Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== ID별로 오브젝트 스토리지 그룹을 삭제합니다

다음 표에 나열된 방법을 사용하여 ID별로 개체 스토리지 그룹을 삭제합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | '/v2.1/objectiam/groups/{id}' | ID별로 오브젝트 스토리지 그룹을 삭제합니다. | "id(string)": 객체 스토리지 그룹의 고유 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


=== 오브젝트 스토리지 사용자

다음 표에 나열된 방법을 사용하여 다음 작업을 수행합니다.

* 오브젝트 스토리지 사용자를 검색, 생성 또는 수정합니다.
* S3 키를 생성하거나 사용자의 S3 키를 검색하거나 키 ID를 기준으로 키를 검색합니다.


|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/objectiam/users' | 오브젝트 스토리지 사용자를 검색합니다. 


| "내려가세요 | '/v2.1/objectiam/users/{id}' | ID별로 오브젝트 스토리지 사용자를 검색합니다. 


| POST를 누릅니다 | '/v2.1/objectiam/users' | 오브젝트 스토리지 사용자를 생성합니다. 


| 'Put' | '/v2.1/objectiam/users/{id}' | ID로 식별되는 오브젝트 스토리지 사용자를 수정합니다. 


| "삭제" | '/v2.1/objectiam/users/{id}' | ID별로 오브젝트 스토리지 사용자를 삭제합니다. 


| "내려가세요 | '/v2.1/objectiam/users/{user_id}/s3keys' | 사용자에게 매핑된 모든 S3 키를 가져옵니다. 


| POST를 누릅니다 | '/v2.1/objectiam/users/{user_id}/s3keys' | S3 키를 생성합니다. 


| "내려가세요 | '/v2.1/objectiam/users/{user_id}/s3keys/{key_id}' | 키 ID별로 S3 키를 가져옵니다. 


| "삭제" | '/v2.1/objectiam/users/{user_id}/s3keys/{key_id}' | 키 ID로 S3 키를 삭제합니다. 
|===


==== 오브젝트 스토리지 사용자 특성

다음 표에서는 오브젝트 스토리지 사용자 특성을 보여 줍니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 오브젝트 스토리지 사용자의 고유 식별자입니다. 


| dissplay_name | 문자열 | 사용자의 표시 이름입니다. 


| '소방' | 문자열 | 사용자가 속한 서브테넌트의 이름입니다. 


| 'Subtenant_id'입니다 | 문자열 | 사용자가 속한 서브테넌트의 식별자입니다. 


| '소작인' | 문자열 | 사용자가 속한 테넌트의 이름입니다. 


| 테넌트_id | 문자열 | 사용자가 속한 테넌트의 식별자입니다. 


| 'objectiam_user_urn'입니다 | 문자열 | URN. 


| 'sg_group_membership'입니다 | 문자열 | NetApp StorageGRID 그룹 멤버쉽 예: "sg_group_membership": ["5d2fb0fb4f47df00015274e3"] 
|===


=== 오브젝트 스토리지 사용자를 검색합니다

다음 표에 나열된 방법을 사용하여 모든 오브젝트 스토리지 사용자 또는 오브젝트 스토리지 사용자의 하위 집합을 검색할 수 있습니다. 'subtenant_id'를 지정하면 해당 서브테넌트에 속한 객체 스토리지 그룹만 반환됩니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectiam/users' | 모든 오브젝트 스토리지 사용자를 검색합니다. | Subtenant_id (string): IAM 사용자/그룹과 연관된 서브테넌트 ID. '오프셋'과 '한계'는 를 참조하십시오 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


==== ID별로 오브젝트 스토리지 사용자를 검색합니다

다음 표에 나열된 메소드를 사용하여 ID별로 사용하는 객체 스토리지를 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectiam/users{id}' | ID별로 오브젝트 스토리지 사용자를 검색합니다. | ID: 객체 저장소 계정 ID입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


==== 오브젝트 스토리지 사용자를 생성합니다

다음 표에 나열된 방법을 사용하여 오브젝트 스토리지 사용자를 생성합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/objectiam/users' | 새 오브젝트 스토리지 사용자를 생성합니다. | 없음 
|===
요청 본문 속성: dissplay_name, subtenant_id, sg_group_membership

* 요청 본문 예: *

....
{
  "display_name": "MyUserName",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "sg_group_membership": [
    "5ed5fa312c356a0001a73840"
  ]
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed603712c356a0001a7386c",
        "action": "create",
        "job_summary": "Activate request is successfully submitted",
        "created": "2020-06-02T07:44:49.647815816Z",
        "updated": "2020-06-02T07:44:49.647815816Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== 오브젝트 스토리지 사용자를 수정합니다

다음 표에 나열된 방법을 사용하여 오브젝트 스토리지 사용자를 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/objectiam/users/{id}' | ID로 식별되는 오브젝트 스토리지 사용자를 수정합니다. | "id": 객체 스토리지 사용자 ID입니다. 
|===
요청 본문 속성: dissplay_name, subtenant_id, sg_group_membership

* 요청 본문 예: *

....
{
  "display_name": "MyModifiedObjectStorageUser",
  "subtenant_id": "5e57a465896bd80001dd4961",
  "sg_group_membership": [
    "5e60754f9b64790001fe937b"
  ]
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed604002c356a0001a73880",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:47:12.205889873Z",
        "updated": "2020-06-02T07:47:12.205889873Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== 모든 S3 키를 오브젝트 스토리지 사용자에게 매핑합니다

다음 표에 나와 있는 방법을 사용하여 모든 S3 키를 오브젝트 스토리지 사용자에게 매핑합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectiam/users/{user_id}/s3keys' | 오브젝트 스토리지 사용자의 S3 키를 생성합니다. | 'user_id(string)': 객체 스토리지 사용자 식별자입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z"
      }
    ]
....


==== 오브젝트 스토리지 사용자의 S3 키를 생성합니다

오브젝트 스토리지 사용자에 대한 S3 키를 생성하려면 다음 목록에 나와 있는 방법을 사용하십시오.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/objectiam/users/{user_id}/s3keys' | 오브젝트 스토리지 사용자의 S3 키를 생성합니다. | 'user_id(string)': 객체 스토리지 사용자 식별자입니다. 
|===
필요한 요청 본문 속성: 'expires'(문자열)


NOTE: 키 만료 날짜/시간은 UTC로 설정되어 있습니다. 나중에 설정해야 합니다.

* 요청 본문 예: *

....
{
  "expires": "2020-04-07T10:40:52Z"
}
....
* 응답 바디 예: *

....
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z",
        "access_key": "PL86KPEBN6XT4T7UHNDE",
        "secret_key": "FlD/YWAM7JMr9gG8pumU8dzvcTLMzLYtUe2lNzcA"
      }
    ]
  }
}
....


==== 오브젝트 스토리지 사용자의 S3 키를 키 ID별로 가져옵니다

다음 표에 나와 있는 방법을 사용하여 오브젝트 스토리지 사용자의 S3 키를 키 ID별로 가져올 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectiam/users/{user_id}/s3keys/{key_id}' | 키 ID별로 S3 키를 가져옵니다.  a| 
* 'user_id(string)': 객체 스토리지 사용자 ID. 예: 5e66c77809a74c0001b89598
* 'key_id(string)': s3 키(예: 5e66de2509a74c0001b895e7)


|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecc7bb9b5d2730001f798fb",
        "display_name": "****************XCXD",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "objectiam_user_id": "5eb2212d1cbe3b000134762e",
        "objectiam_user": "MyUser",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "expires": "2020-05-27T00:00:00Z"
      }
    ]
  }
}
....


==== 키 ID로 S3 키를 삭제합니다

다음 표에 나열된 방법을 사용하여 키 ID별로 S3 키를 삭제합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | '/v2.1/objectiam/users/{user_id}/s3keys/{key_id}' | 키 ID로 S3 키를 삭제합니다.  a| 
* 'user_id(string)': 객체 스토리지 사용자 ID. 예: 5e66c77809a74c0001b89598
* 'key_id(string)': s3 키(예: 5e66de2509a74c0001b895e7)


|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
No content to return for succesful execution
....


=== 오브젝트 스토리지 계정

다음 표에 나열된 방법을 사용하여 다음 작업을 수행합니다.

* 오브젝트 스토리지 계정을 검색, 활성화 또는 수정합니다.
* S3 버킷을 생성합니다.


|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/objectstorage/accounts' | 오브젝트 스토리지 계정을 검색합니다. 


| "내려가세요 | '/v2.1/objectstorage/accounts/{id}' | ID별로 오브젝트 스토리지 계정을 검색합니다. 


| POST를 누릅니다 | '/v2.1/objectstorage/accounts' | 오브젝트 스토리지 계정을 생성합니다. 


| 'Put' | '/v2.1/objectstorage/accounts/{id}' | ID로 식별되는 오브젝트 스토리지 계정을 수정합니다. 


| "삭제" | '/v2.1/objectstorage/accounts/{id}' | ID로 식별되는 오브젝트 스토리지 계정을 수정합니다. 


| "내려가세요 | '/v2.1/objectstorage/버킷' | S3 버킷을 준비합니다. 


| POST를 누릅니다 | '/v2.1/objectstorage/버킷' | S3 버킷을 생성합니다. 
|===


==== 오브젝트 스토리지 계정 특성

다음 표에는 오브젝트 스토리지 계정 특성이 나와 있습니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 오브젝트 스토리지 사용자의 고유 식별자입니다. 


| 'Subtenant_id'입니다 | 문자열 | 서브테넌트 객체 인스턴스의 식별자입니다. 


| quota_gb입니다 | 정수 | 공유 또는 디스크의 크기입니다. 
|===


=== 모든 오브젝트 스토리지 계정을 검색합니다

다음 표에 나열된 방법을 사용하여 모든 오브젝트 스토리지 계정 또는 오브젝트 스토리지 계정의 하위 집합을 검색할 수 있습니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectstorage/accounts' | 모든 오브젝트 스토리지 사용자를 검색합니다. | '오프셋' 및 '한계' – 을 참조하십시오 link:seapiref_netapp_service_engine_rest_apis.html#pagination>["공통 페이지 매김"] 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예 *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 19,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtenant",
        "subtenant": " MySubtenant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": "E- MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
}
....


==== ID별로 오브젝트 스토리지 계정을 검색합니다

다음 표에 나열된 방법을 사용하여 ID별로 개체 저장소 계정을 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectstorage/accounts/{id}' | ID별로 오브젝트 스토리지 계정을 검색합니다. | ID: 객체 저장소 계정 ID입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtennant",
        "subtenant": " MySubtennant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": " MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
....


==== 오브젝트 스토리지 계정을 활성화합니다

다음 표에 나열된 방법을 사용하여 개체 저장소 계정을 활성화합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/objectstorage/accounts' | 오브젝트 스토리지 서비스를 활성화합니다. | 없음 
|===
요청 본문 속성:'Subtenant_id, quota_GB'입니다

* 요청 본문 예: *

....
{
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 20
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed608542c356a0001a73893",
        "action": "create",
        "job_summary": "Activate request for Sub Tenant MyNewSubtenant is successfully submitted",
        "created": "2020-06-02T08:05:40.017362022Z",
        "updated": "2020-06-02T08:05:40.017362022Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== 오브젝트 스토리지 계정을 수정합니다

다음 표에 나열된 방법을 사용하여 개체 스토리지 계정을 수정합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| 'Put' | '/v2.1/objectstorage/accounts/{id}' | 오브젝트 스토리지 서비스 수정(예: 할당량 변경) | "id(string)": 객체 저장소 계정 ID입니다. 
|===
요청 본문 속성: name, subtenant_id, quota_GB

* 요청 본문 예: *

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed609162c356a0001a73899",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T08:08:54.841652098Z",
        "updated": "2020-06-02T08:08:54.841652098Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


==== 오브젝트 스토리지 계정을 삭제합니다

오브젝트 스토리지 계정을 삭제하려면 먼저 연결된 모든 그룹, 사용자 및 버킷을 삭제해야 합니다. 다음 표에 나열된 방법을 사용하여 개체 저장소 계정을 삭제합니다.


NOTE: S3 호환 유틸리티를 사용하여 버킷을 삭제합니다. NetApp 서비스 엔진에서 Bucket을 삭제할 수 없습니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "삭제" | '/v2.1/objectstorage/accounts/{id}' | 오브젝트 스토리지 계정을 삭제합니다. | "id(string)": 객체 저장소 계정 ID입니다. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "action": "string",
        "object_id": "5d2fb0fb4f47df00015274e3",
        "object_type": "string",
        "status": "string",
        "status_detail": "string",
        "last_error": "string",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "link": "string"
      }
    ]
  }
}
....


=== 오브젝트 스토리지 버킷

다음 표의 API를 사용하여 오브젝트 스토리지 버킷을 생성하고 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 


| "내려가세요 | '/v2.1/objectstorage/버킷' | 오브젝트 스토리지 버킷 검색 


| POST를 누릅니다 | '/v2.1/objectstorage/버킷' | 오브젝트 스토리지 버킷을 생성합니다. 
|===


==== 오브젝트 스토리지 버킷 특성

다음 표에는 오브젝트 스토리지 버킷 특성이 나와 있습니다.

|===
| 속성 | 유형 | 설명 


| "아이드" | 문자열 | 오브젝트 스토리지 사용자의 고유 식별자입니다. 


| 이름 | 문자열 | 버킷 이름입니다. 


| 'Subtenant_id'입니다 | 문자열 | 버킷이 속한 서브테넌트의 식별자입니다. 
|===


==== S3 버킷을 검색합니다

다음 표에 나열된 방법을 사용하여 S3 버킷을 검색합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| "내려가세요 | '/v2.1/objectstorage/버킷' | S3 버킷을 검색합니다. | 'Subtenant_id': 버킷을 소유하는 서브테넌트. 
|===
요청 본문 속성: 없음

* 요청 본문 예: *

....
none
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "creationTime": "2020-06-02T08:13:25.695Z",
        "name": "mybucket"
      }
    ]
  }
}
....


==== S3 버킷을 생성합니다

다음 표에 나와 있는 방법을 사용하여 S3 버킷을 생성합니다.


NOTE: 버킷을 생성하려면 먼저 서브테넌트의 오브젝트 스토리지 계정이 있어야 합니다.

|===
| HTTP 메서드 | 경로 | 설명 | 매개 변수 


| POST를 누릅니다 | '/v2.1/objectstorage/버킷' | S3 버킷을 생성합니다. | 없음 
|===
필요한 요청 본문 속성:

* '이름'(문자열): S3 버킷 이름(소문자 또는 숫자만)
* Subtenant_id(string): S3 버킷이 속한 서브테넌트의 ID입니다


* 요청 본문 예: *

....
{
  "name": "mybucket",
  "subtenant_id": "5ecefbbef418b40001f20bd6"
}
....
* 응답 바디 예: *

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed60a232c356a0001a7389e",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T08:13:23.105015108Z",
        "updated": "2020-06-02T08:13:23.105015108Z",
        "object_id": "5ed60a232c356a0001a7389f",
        "object_type": "sg_buckets",
        "object_name": "mybucket",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....