---
sidebar: sidebar 
permalink: sewebiug_working_with_block_storage_overview.html 
keywords: netapp, keystone, working, block, storage, overview, 
summary: Keystone 블록 스토리지 작업 개요 
---
= 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
블록 스토리지 시스템에서 데이터 스토리지는 고유한 식별자가 포함된 개별 조각으로 나뉩니다. NetApp 서비스 엔진은 블록 데이터 스토리지를 블록 저장소로, 개별 요소를 디스크로 지칭합니다.

블록 저장소는 서브테넌트에 속하며 영역 내에서 지정됩니다(서브테넌트당 영역당 블록 저장소 1개). 블록 저장소에는 iSCSI 또는 FC 프로토콜을 통해 디스크에 액세스하는 데 사용되는 네트워킹 특성(예: IP 주소 및 VLAN ID)이 있습니다. 블록 저장소에서 재해 복구 DP를 활성화할 수 있습니다. 자세한 내용은 을 참조하십시오 link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery.html["재해 복구"].

블록 저장소를 사용하려면 먼저 초기화해야 합니다. 블록 스토리지를 사용할 수 있고 초기화되지 않은 경우 디스크 생성 프로세스의 일부로 블록 저장소에 첫 번째 디스크를 생성하기 전에 블록 스토리지를 초기화할 수 있습니다.

디스크는 블록 저장소에 생성됩니다. 디스크에는 용량 및 관련 서비스 수준을 포함하여 다양한 구성 가능한 속성이 있습니다. 과 같은 DP 옵션 link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#snapshots["스냅샷 수"] 및 link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery["재해 복구"] 디스크에 대해 활성화할 수 있습니다.

디스크에 대한 액세스는 호스트 그룹을 통해 제어됩니다. 호스트 그룹은 이니시에이터 노드 이름으로 구성되며, 하나 이상의 호스트 그룹을 디스크에 매핑하여 디스크에 액세스할 수 있는 이니시에이터를 정의할 수 있습니다.

호스트 그룹:

* 프로토콜에 따라 다릅니다. 다음 중 하나일 수 있습니다.
+
** FC 프로토콜 호스트 그룹: FC WWPN(World Wide Port Name)인 이니시에이터로 구성됩니다. 예: '20:56:00:a0:98:5c:0d:da').
** iSCSI 프로토콜 호스트 그룹: IQN(iSCSI 정규화된 이름)인 이니시에이터로 구성됩니다. 예: 'iqn.1998-01.com.vmware:esx2`.


* 별칭/이니시에이터 쌍으로 구성됩니다. 별칭을 사용하면 이니시에이터를 쉽게 식별할 수 있습니다. 예를 들어, 'esxserver1'입니다.
* 이니시에이터 없이 생성할 수 있습니다. 빈 호스트 그룹은 디스크에 자리 표시자로 매핑할 수 있지만 디스크에 액세스할 수 있도록 완전히 정의해야 합니다. 호스트 그룹을 사용하면 다음을 수행할 수 있습니다.
* 여러 디스크를 동일한 이니시에이터 세트에 매핑
* 여러 디스크에 걸쳐 이니시에이터 세트를 업데이트합니다.


이 섹션에서는 다음에 대한 정보를 다룹니다.

* 호스트 그룹 작업:
+
** 호스트 그룹을 봅니다
** 호스트 그룹을 생성합니다
** 호스트 그룹 이니시에이터를 수정합니다
** 호스트 그룹을 삭제합니다


* 디스크 작업:
+
** 디스크를 봅니다
** 새 디스크를 만듭니다
** 스냅샷으로부터 디스크를 생성합니다
** 디스크를 수정합니다
** 디스크를 삭제합니다
** 디스크의 임시 스냅샷을 생성합니다



