---
sidebar: sidebar 
permalink: sewebiug_managing_azure_netapp_accounts.html 
keywords: netapp, keystone, managing, azure, accounts, 
summary: Azure NetApp 계정 관리 
---
= Azure NetApp 계정 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 섹션에서는 Azure NetApp 계정을 관리하는 방법을 설명합니다.


NOTE: Azure NetApp 계정을 관리하려면 고객 관리자 액세스 권한이 필요합니다.

이 섹션의 내용:

* Azure NetApp 계정 목록을 봅니다
* Azure NetApp 계정을 추가합니다
* Azure NetApp 계정 세부 정보를 수정합니다
* Azure NetApp 계정을 삭제합니다




== Azure NetApp 계정 목록을 봅니다

Azure NetApp 계정 목록에는 로그인한 사용자가 액세스할 수 있는 모든 Azure NetApp 계정의 목록이 표시됩니다. 목록을 보려면 메뉴에서 * administration > Azure NetApp Accounts * 를 선택합니다.

목록에는 각 Azure NetApp 계정에 대한 간단한 정보가 표시됩니다. 각 Azure NetApp 계정 옆의 작업 아이콘을 사용하여 Azure NetApp 계정을 수정하거나 삭제할 수 있습니다.



== Azure NetApp 계정을 추가합니다

이 섹션에서는 Azure NetApp 계정을 추가하는 방법을 설명합니다.

.시작하기 전에
필요한 사항:

* Azure NetApp 계정이 속하는 하위 테넌트입니다
* ANF 인스턴스
* Azure 위치(지역)
* Azure 리소스 그룹
* 계정 이름입니다


.단계
. 메뉴에서 * 관리 > Azure NetApp Accounts * 를 선택합니다.
. Create * 를 클릭합니다.
. Azure NetApp 계정 생성 대화 상자에서 하위 테넌트, Azure 위치(지역), Azure 리소스 그룹 및 Azure NetApp 계정의 이름을 지정합니다.
. 필요한 경우 계정에 태그를 추가합니다.
. Create * 를 클릭합니다. 성공적으로 생성되었으면 계정 상태가 성공합니다(Azure NetApp 계정 목록에서 볼 수 있음).




== Azure NetApp 계정 태그를 수정합니다

이 방법을 사용하여 Azure NetApp 계정과 연결된 태그를 수정할 수 있습니다.

.단계
. 메뉴에서 * 관리 > Azure NetApp Accounts * 를 선택합니다.
. 목록에서 Azure NetApp 계정을 찾고 편집 아이콘을 클릭합니다.
. Azure NetApp 계정 관리 대화 상자에서 필요에 따라 태그를 추가, 제거 또는 편집합니다.
. Update * 를 클릭합니다.




== Azure NetApp 계정을 삭제합니다

이 방법을 사용하여 Azure NetApp 계정을 삭제합니다.

.단계
. 메뉴에서 * 관리 > Azure NetApp Accounts * 를 선택합니다.
. 목록에서 Azure NetApp 계정을 찾고 삭제 아이콘을 클릭합니다.
. 삭제 확인 대화 상자에서 삭제할 Azure NetApp 계정의 이름을 입력합니다.
. 확인 * 을 클릭합니다.

