---
sidebar: sidebar 
permalink: sewebiug_create_file_share_from_snapshot.html 
keywords: netapp, keystone, create, file share, snapshot 
summary: 스냅샷에서 파일 공유를 생성합니다 
---
= 스냅샷에서 파일 공유를 생성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
기존 스냅샷에서 새 파일 공유를 생성할 수 있습니다. 스냅샷에서 복제된 새 파일 공유는 스냅샷이 생성된 파일 공유와 동일한 속성을 갖습니다.

.단계
. 왼쪽 탐색 창에서 * 파일 서비스 * 를 선택하고 * 공유 * 를 선택합니다.
. Create Share * 를 클릭하고 * Clone from snapshot * 을 선택합니다. 또는 클론 복제에 사용할 스냅샷의 공유를 알고 있는 경우 파일 공유를 찾고 그 옆에 있는 복사 버튼을 클릭합니다. 공유는 작동 상태여야 합니다. 개체 상태에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["개체 상태"]. 스냅샷에서 공유 생성 * 화면이 테넌트에 대한 모든 파일 공유와 함께 표시됩니다. 영역, 영역 및 하위 테넌트별로 파일 공유를 필터링할 수 있습니다. 작동 중인 파일 공유를 선택할 수 있습니다.
. 원하는 파일 공유 옆의 확인란을 선택하고 * 다음 * 을 클릭합니다. 파일 공유에 대한 스냅샷이 표시됩니다.
+

NOTE: 선택한 파일 공유에 대해 SnapCenter 서비스 엔진 외부의 NetApp 환경에서 일부 스냅샷이 생성된 경우, 선택한 스냅샷을 가져올 수 있습니다. 가져온 스냅샷을 선택하고 새 파일 공유를 복제할 수 있습니다.

+
특정 스냅샷을 검색하거나 스케줄 유형을 선택하여 스냅샷을 필터링할 수 있습니다.

. 복제할 스냅샷 옆의 확인란을 선택하고 * 다음 * 을 클릭합니다. 새 파일 공유는 선택한 스냅샷의 속성을 상속합니다.
. 이름 * 과 * 공유 경로 * 를 추가합니다. 서비스 수준 할당 * 과 같은 다른 설정을 업데이트하고 * 생성 * 을 클릭합니다. 요구 사항에 가장 적합한 서비스 수준을 선택하십시오.


.작업을 마친 후
* CIFS 유형 공유에만 해당: 호스트 이름으로 공유를 사용할 수 있도록 하려면 도메인 관리자가 CIFS 서버 이름 및 IP 주소로 DNS 레코드를 업데이트해야 합니다. 그렇지 않으면 IP 주소를 통해서만 공유에 액세스할 수 있습니다. 예를 들면 다음과 같습니다.
+
** DNS 레코드가 업데이트된 경우 호스트 이름 또는 IP를 사용하여 과 같은 공유에 액세스합니다 file://hostname/share["호스트 이름\공유"^] 또는 file://IP/share["IP\\share"^]
** DNS 레코드가 업데이트되지 않은 상태에서 IP 주소를 사용하여 공유에 액세스해야 합니다 file://IP/share["IP\\share"^]


* * 공유 생성 * 은 비동기 작업으로 실행됩니다. 다음을 수행할 수 있습니다.
+
** 작업 목록에서 작업의 상태를 확인합니다. 작업 추적에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["여기"].
** 작업이 완료되면 * Shares * 목록에서 공유 상태를 확인합니다.



