---
sidebar: sidebar 
permalink: sewebiug_managing_tenants_and_subtenants.html 
keywords: netapp, keystone, managing, subtenants, 
summary: 하위 테넌트를 관리하는 Keystone 
---
= 테넌트 및 하위 테넌트 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 서비스 엔진을 사용하여 테넌트 및 하위 테넌트를 확인하고 관리할 수 있습니다. 초기 테넌시는 서비스 공급자/파트너 및 테넌트에 대해 NetApp 지원을 통해 설정됩니다. 지역, 영역 및 구독은 이미 지원 팀에 의해 구성되었으며 테넌시에 테넌트 및 하위 테넌트를 생성할 때 사용할 수 있습니다.



== 테넌트

파트너 관리자인 경우 * 관리 * > * 테넌트 * 에서 테넌트를 생성, 수정 및 삭제할 수 있습니다. 테넌트 관리자는 해당 테넌트 구독 및 하위 테넌트만 볼 수 있습니다. 파트너 테넌시에 있는 테넌트의 경우 네트워크를 정의할 수도 있습니다.



=== 테넌트를 생성합니다

파트너 관리자인 경우 테넌트를 생성할 수 있습니다. 각 테넌트의 네트워크를 생성하고 관리할 수도 있습니다. 네트워크 작성에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_define_network_configurations.html["서브넷을 사용하여 네트워크 구성을 정의합니다"].

.단계
. Create Tenant * 를 클릭합니다.
. 이름과 코드를 추가합니다. 테넌트를 나타내는 코드는 NetApp Service Engine 인스턴스 내에서 고유해야 하며 소문자로 구성됩니다.
. Create * 를 클릭합니다.



NOTE: 기존 테넌트의 이름과 설명만 수정할 수 있습니다. 또한 하위 테넌트 또는 연결된 스토리지 구성 요소가 있는 테넌트는 삭제할 수 없습니다.



== 하위 테넌트

파트너 관리자 또는 테넌트 관리자는 하위 테넌트를 보고 관리할 수 있습니다.



=== 서브테넌트를 생성합니다

파트너 관리자 또는 테넌트 관리자인 경우 * administration * > * Subtenant * 에서 서브테넌트를 생성, 수정 및 삭제할 수 있습니다. 각 서브테넌트에 대한 네트워크를 만들고 관리할 수도 있습니다.

네트워크 작성에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_define_network_configurations.html["서브넷을 사용하여 네트워크 구성을 정의합니다"].

.단계
. Create Subtenant * 를 클릭합니다.
. 이름과 코드를 추가합니다. 서브테넌트를 나타내는 코드는 NetApp Service Engine 인스턴스 내에서 고유해야 하며 소문자로 구성됩니다.
. Create * 를 클릭합니다.



NOTE: 기존 서브테넌트의 이름만 수정할 수 있습니다. 또한 연결된 스토리지 구성 요소가 있는 서브테넌트는 삭제할 수 없습니다.
