---
sidebar: sidebar 
permalink: sewebiug_managing_azure_volumes.html 
keywords: netapp, keystone, managing, azure, volumes, 
summary: Keystone Azure 볼륨 관리 
---
= Azure 볼륨 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 섹션에서는 Azure 볼륨을 관리하는 방법에 대해 설명합니다.


NOTE: Azure 볼륨을 관리하려면 고객 관리자 액세스 권한이 필요합니다.

이 섹션에서는 다음 작업을 수행하는 방법을 설명합니다.

* Azure 볼륨 목록을 봅니다.
* Azure 볼륨을 추가합니다.
* Azure 볼륨 세부 정보를 수정합니다.
* Azure 볼륨을 삭제합니다.




=== Azure 볼륨 목록을 봅니다

Azure Volumes 목록에는 지정된 서브테넌트 및 위치에 대한 Azure 볼륨 풀 목록이 표시됩니다. 목록을 보려면 메뉴에서 * 파일 서비스 > Azure Volumes * 를 선택합니다.

목록에는 각 Azure 볼륨에 대한 간단한 정보가 표시됩니다. 각 Azure 볼륨 옆의 작업 아이콘을 사용하여 Azure 볼륨을 수정 또는 삭제할 수 있습니다.



=== Azure 볼륨을 추가합니다

이 섹션에서는 Azure 볼륨을 추가하는 방법을 설명합니다.

필요한 사항:

* Azure 볼륨이 속한 하위 테넌트입니다
* ANF 계정
* Azure VNet(Virtual Network) 및 서브넷입니다
* 볼륨을 수용할 용량 풀입니다
* 볼륨의 이름입니다
* 파일 경로
* 볼륨의 할당량(크기)입니다


.단계
. 메뉴에서 * 파일 서비스 > Azure Volumes * 를 선택합니다.
. Create * 를 클릭합니다.
. Azure 볼륨 생성 대화 상자에서 서브테넌트, ANF 계정, VNET, 서브넷을 지정합니다. 용량 풀, 볼륨의 이름, 파일 경로 및 할당량입니다. 성공적인 볼륨 생성을 위해 고유한 파일 경로를 입력해야 합니다.
. 필요한 경우 볼륨에 태그를 추가합니다.
. Create * 를 클릭합니다. Azure 볼륨이 생성되면 볼륨의 상태가 'ucceed(ucceed)'로 변경됩니다(Azure Volumes(Azure 볼륨) 목록에서 볼 수 있음).




=== Azure 볼륨 세부 정보를 수정합니다

이 방법을 사용하여 Azure 볼륨의 세부 정보를 수정할 수 있습니다. 파일 경로 및 할당량을 수정하고 태그를 추가하거나 제거할 수 있습니다.

.단계
. 메뉴에서 * 파일 서비스 > Azure Volumes * 를 선택합니다.
. 목록에서 Azure 볼륨을 찾고 편집 아이콘을 클릭합니다.
. Azure 볼륨 관리 대화 상자에서 필요한 사항을 변경합니다. 파일 경로 또는 할당량을 수정하는 경우 파일 경로가 고유하고 할당량이 풀의 사용 가능한 할당량을 초과하지 않는지 확인합니다.
. Update * 를 클릭합니다.




=== Azure 볼륨을 삭제합니다

이 방법을 사용하여 Azure 볼륨을 삭제합니다.

.단계
. 메뉴에서 * 파일 서비스 > Azure Volumes * 를 선택합니다.
. 목록에서 Azure 볼륨을 찾고 삭제 아이콘을 클릭합니다.
. 삭제 확인 대화 상자에서 삭제할 Azure 볼륨의 이름을 입력합니다.
. 확인 * 을 클릭합니다.

