---
sidebar: sidebar 
permalink: sewebiug_managing_subscriptions.html 
keywords: netapp, keystone, managing, subscriptions, 
summary: Keystone 구독 관리 
---
= 구독 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
구독 관리에는 NetApp Keystone 구독 및 테넌트 구독 서비스에 서비스 수준을 할당하거나 NetApp 서비스 엔진 인터페이스를 사용하여 서비스 수준에 용량을 할당 및 변경하는 작업이 포함됩니다.

서비스 공급자/파트너와 NetApp, 테넌트 구독 간의 관계로 표시되는 구독 서비스는 서비스 공급자와 해당 테넌트 및 하위 테넌트(최종 고객) 간의 관계를 나타냅니다. NetApp 관리자 또는 GSSC가 파트너 및 테넌트를 위해 Keystone 가입 서비스 서비스를 생성하면 스토리지 할당이 완료되었다는 것을 의미합니다. 하지만 서비스 수준이 생성되고 해당 용량 할당이 완료되지 않는 한, 서브테넌트 또는 최종 고객이 스토리지를 사용할 수 없습니다. 파트너 관리자는 Keystone 가입 서비스 및 테넌트 구독에 대한 스토리지를 관리할 수 있습니다. 테넌트 관리자는 자신의 테넌시에 대한 테넌트 구독 세부 정보와 서비스만 볼 수 있습니다.



== Keystone 가입 관리

파트너 관리자는 * 서브스크립션 * > * Keystone 가입 * 에서 Keystone 가입 서비스를 확인 및 관리할 수 있습니다. * Keystone 가입 * 은 NetApp 관리자가 파트너를 위해 작성한 Keystone 가입 서비스를 나타냅니다. 파트너 관리자는 Keystone 가입 서비스를 확인하고 다음에 대한 서비스 요청을 생성할 수 있습니다.

* 서브스크립션 용량을 늘립니다
* 구독에 서비스 추가(서비스 수준 및 용량 할당)


서비스 요청은 지원 팀에서 수신 및 처리합니다.

또한 구독 중인 데이터 보호 및 고급 보호 서비스를 별도의 탭에서 확인 및 관리할 수 있습니다. 자세한 내용은 을 참조하십시오 link:index.html#flex-subscription["데이터 보호 및 데이터 보호 고급"].



=== 서브스크립션 용량을 늘립니다

구독한 서비스 수준에 대해 할당된 용량을 늘려 성장 요구 사항을 충족할 수 있습니다.

.단계
. 드롭다운 메뉴에서 용량을 늘릴 구독을 선택합니다.
. 원하는 서비스 수준에 대해 * 용량 증가 * 를 클릭합니다.
. 필요한 용량(TiB)을 지정합니다.
. [확인]을 클릭합니다. [Keystone 구독 관리] 페이지로 돌아갑니다.
. 변경 내용 제출 * 을 클릭합니다. GSSC의 용량을 늘리기 위해 서비스 요청을 생성합니다. 메시지에 표시된 SR 번호로 서비스 요청의 진행 상황을 확인하고 추적할 수 있습니다. 추적에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_track_a_service_request.html["서비스 요청을 추적합니다"].




=== 구독에 서비스를 추가합니다

구독에 서비스를 추가할 수 있습니다. 서비스 추가에는 서비스 수준을 구독에 할당하고 동일한 서비스 수준에 대한 용량을 지정하는 작업이 포함됩니다.

각 구독에는 각 서비스 수준 중 하나가 있을 수 있습니다. 예를 들어 구독에 이미 Extreme 및 Standard 서비스가 포함되어 있는 경우 Premium 또는 Block 서비스를 추가할 수 있습니다.

.단계
. 드롭다운 메뉴에서 구독에 추가할 서비스 수준을 선택합니다.
. 서비스 추가 * 를 클릭합니다.
. 드롭다운 메뉴에서 가입할 서비스 수준(예: Extreme-Tiering)을 선택하고 서비스 수준에 할당할 용량(TiB)을 추가합니다.
. 확인 * 을 클릭합니다. Keystone 구독 관리 페이지로 돌아갑니다.
. 변경 내용 제출 * 을 클릭합니다. GSSC에 대한 서비스 요청이 생성됩니다. 서비스 수준을 구독에 할당합니다. 메시지에 표시된 SR 번호로 서비스 요청의 진행 상황을 확인하고 추적할 수 있습니다.


추적에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_track_a_service_request.html["서비스 요청을 추적합니다"].



== 테넌트 가입을 관리합니다

파트너 관리자인 경우 * 서브스크립션 * > * 테넌트 구독 * 에서 테넌트 구독을 생성, 보기 및 업데이트할 수 있습니다. 테넌트 관리자는 구독만 볼 수 있습니다.



=== 테넌트 가입을 생성하고 편집합니다

테넌트에 대한 새 구독을 만들 수 있습니다.

.단계
. 새 구독 * 을 클릭합니다.
. 지역, 구역, 가입 기간, 요금제 및 기타 세부 정보를 지정합니다. 테넌트 구독은 선택한 영역에 따라 Keystone 구독에 할당됩니다. 이는 각 Keystone 가입이 지역에 묶여 있기 때문입니다.
+

NOTE: 중복되는 가입은 만들 수 없습니다. 구독은 지정된 시작 날짜 이전부터 시작되므로 시작 날짜는 최소한 다음 날이어야 합니다. 또한 현재 날짜로부터 30일을 초과할 수 없습니다.

. Create * 를 클릭합니다.


구독을 삭제할 수 없습니다. 기존 테넌트 가입만 편집하고 새 서비스 수준을 추가하고, 서비스 수준에 대해 커밋된 용량을 늘리고, 태그에 태그를 추가할 수 있습니다.

파트너 관리자인 경우 테넌트 구독을 편집할 수 있습니다. 구독에 새 서비스 수준을 추가하고 이미 추가된 서비스 수준의 용량을 편집할 수 있습니다. 새 서비스 수준을 추가하려면 다음 단계를 수행하십시오.

.단계
. "+" 아이콘을 클릭하여 편집할 구독을 선택합니다.
. 가입에 새 서비스 수준 추가 * 페이지에서 새 서비스 수준을 선택하고 필요한 용량을 추가합니다. 서비스 수준이 이미 추가된 경우에는 추가하거나 삭제할 수 없습니다.
. Update * 를 클릭합니다.


구독의 태그 아이콘을 클릭하여 태그를 추가할 수도 있습니다.

구독에 이미 할당된 서비스 수준에 대해 서비스 용량을 편집하려면 다음 단계를 따르십시오.

.단계
. v 아이콘을 클릭하여 편집할 가입을 확장합니다. 해당 구독의 서비스 수준이 표시됩니다.
. 해당 편집 펜 아이콘을 클릭하여 편집할 서비스 수준을 선택합니다.
. TiB의 용량을 늘리거나 줄여 Rate Plan을 변경한다.
. Update * 를 클릭합니다.

