---
sidebar: sidebar 
permalink: sewebiug_managing_azure_capacity_pools.html 
keywords: netapp, keystone, managing, azure, capacity, pools, 
summary: Keystone Azure 용량 풀 관리 
---
= Azure 용량 풀 관리
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 섹션에서는 Azure 용량 풀을 관리하는 방법에 대해 설명합니다.


NOTE: Azure 용량 풀을 관리하려면 고객 관리자 액세스가 필요합니다.

이 섹션에서는 다음 작업을 수행하는 방법을 설명합니다.

* Azure 용량 풀 목록을 봅니다
* Azure 용량 풀을 추가합니다
* Azure 용량 풀 세부 정보를 수정합니다
* Azure 용량 풀을 삭제합니다




=== Azure 용량 풀 목록을 봅니다

Azure 용량 풀 목록에는 지정된 서브테넌트 및 위치에 대한 용량 풀 목록이 표시됩니다. 목록을 보려면 메뉴에서 * 파일 서비스 > Azure Capacity Pools * 를 선택합니다.

목록에는 각 Azure 용량 풀에 대한 간단한 정보가 표시됩니다. 각 Azure 용량 풀 옆에 있는 작업 아이콘을 사용하여 Azure 용량 풀을 수정하거나 삭제할 수 있습니다.



=== Azure 용량 풀을 추가합니다

이 섹션에서는 Azure 용량 풀을 추가하는 방법에 대해 설명합니다.

필요한 사항:

* 용량이 속한 서브테넌트입니다
* ANF 계정입니다
* 서비스 레벨
* 용량 풀의 이름입니다
* 풀의 크기입니다


.단계
. 메뉴에서 * 파일 서비스 > Azure Capacity Pools * 를 선택합니다.
. Create * 를 클릭합니다.
. Azure 용량 풀 생성 대화 상자에서 서브테넌트, ANF 계정, 서비스 레벨, 이름 및 크기를 지정합니다.
. 필요한 경우 용량 풀에 태그를 추가합니다.
. Create * 를 클릭합니다. 용량 풀이 생성되면 상태가 'ucceed'로 변경됩니다(Azure Capacity Pools 목록에서 확인 가능).




=== Azure 용량 풀 세부 정보를 수정합니다

이 방법을 사용하여 Azure 용량 풀의 세부 정보를 수정할 수 있습니다. 풀의 크기에 따라 서비스 수준을 수정할 수 있으며 태그를 추가하거나 제거할 수 있습니다.

.단계
. 메뉴에서 * 파일 서비스 > Azure Capacity Pools * 를 선택합니다.
. 목록에서 Azure 용량 풀을 찾고 편집 아이콘을 클릭합니다.
. Azure 용량 풀 관리 대화 상자에서 필요에 따라 변경합니다.
. Update * 를 클릭합니다.




=== Azure 용량 풀을 삭제합니다

이 방법을 사용하여 Azure 용량 풀을 삭제합니다.

.단계
. 메뉴에서 * 파일 서비스 > Azure Capacity Pools * 를 선택합니다.
. 목록에서 Azure 용량 풀을 찾고 삭제 아이콘을 클릭합니다.
. 삭제 확인 대화 상자에서 삭제할 Azure 용량 풀의 이름을 입력합니다.
. 확인 * 을 클릭합니다.

