---
sidebar: sidebar 
permalink: sewebiug_define_network_configurations.html 
keywords: netapp, keystone, subnet, subtenant, network, tenant network, IPspace, VLAN, port 
summary: 서브넷을 생성하고 삭제합니다 
---
= 테넌트 및 하위 테넌트에 대한 네트워크 구성을 정의합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
서비스 공급자 또는 파트너 관리자는 가입 영역에 따라 테넌트의 네트워크 구성을 정의하고 VLAN을 각 네트워크 구성에 할당할 수 있습니다. 또한 동일한 존과 테넌시에 속하는 각 VLAN을 가진 서브넷을 생성하고 해당 테넌시에 있는 서브테넌트에 할당할 수 있습니다.

사전 구성된 테넌트 네트워크는 서브넷을 생성해야 합니다. 서브테넌트 또는 최종 고객이 파일 서버 또는 블록 저장소를 프로비저닝하는 경우 서브넷이 필요합니다. 파일 및 블록 스토리지 VM은 NetApp 서비스 엔진 의 서브테넌트가 소유하지만 ONTAP에서 IPspace가 소유합니다. 서브테넌트 레벨에서 네트워킹 경계를 정의할 경우 NetApp 서비스 엔진의 서브테넌트는 해당 영역에 대한 단일 ONTAP IPspace에 매핑됩니다. 이렇게 하면 위험이 제거되고 두 개의 개별 하위 테넌트가 동일한 VLAN ID를 선택하지 않고 동일한 IPspace에서 종료되도록 할 수 있습니다.

* 각 영역에 여러 개의 서브넷이 생성될 수 있습니다. 테넌시의 각 영역에 대해 할당된 VLAN 목록이 있습니다. 사용 가능한 모든 VLAN에 대해 해당 서브넷을 생성할 수 있습니다. 서브넷과 VLAN 간에는 1:1 매핑이 있다. 반면 서브넷과 영역 사이에 많은 매핑이 있습니다.
* 하나의 테넌트는 여러 개의 서브넷을 가질 수 있으며, 한 영역의 사용 가능한 각 VLAN에 대해 하나씩 가질 수 있습니다. 각 존에 대한 단일 네트워크 구성 아래에 표시됩니다.
* 각 네트워크 서브넷마다 하나의 VLAN만 있을 수 있습니다. 각 네트워크 구성에는 사용 가능한 VLAN 목록이 표시됩니다.
* 서브테넌트의 영역 및 VLAN 조합에 대해 하나의 서브넷만 생성할 수 있습니다.



NOTE: 테넌트 관리자는 해당 테넌트의 테넌시와 서브넷에 대한 네트워크 구성만 볼 수 있습니다.



== 테넌트의 네트워크 구성을 정의합니다

파트너 관리자는 각 테넌트에 대해 네트워크 구성을 생성할 수 있습니다. 구성 가능하고 고유한 VLAN 풀은 요구 사항에 따라 각 테넌트에 할당될 수 있습니다. 테넌트가 삭제되면 해당 테넌트와 연결된 VLAN이 다시 테넌트 VLAN 풀로 해제됩니다.

.시작하기 전에
* 테넌트가 생성되었는지 확인합니다
* 존, VLAN, 서브넷 CIDR 및 포트 재정의 구성을 알고 있어야 합니다


.단계
. administration * > * Tenants * 에서 필요한 테넌트를 선택합니다.
. 네트워크 아이콘을 클릭합니다. 네트워크 화면이 테넌트에 대한 네트워크 구성 목록과 함께 표시됩니다.
. 네트워크 생성 * 을 클릭합니다. 해당하는 경우 존, VLAN 및 포트 재정의를 지정합니다. 포트 재정의가 정의된 경우 드롭다운에서 할당된 포트를 선택합니다. 해당 테넌트의 모든 네트워크 연결에 대해 이 포트는 기본 포트가 아니라 사용됩니다.
+

NOTE: 포트 재정의는 영역 구성 중에 지원 팀에 의해 구성됩니다. 포트 재정의가 지정되지 않은 경우 네트워크는 기본 포트를 사용하고 해당 테넌트에 대한 새 VLAN을 생성합니다.

. Create * 를 클릭합니다. 새 네트워크 구성이 네트워크 화면에 테넌트에 대해 나열됩니다.


영역에 대한 네트워크 구성이 생성된 경우 새 VLAN만 네트워크 구성에 할당할 수 있습니다. * + * 아이콘을 클릭하고 VLAN 및 포트 재정의 세부 정보를 추가합니다. Update * 를 클릭합니다.



== 서브테넌트에 대한 서브넷을 생성합니다

파트너 관리자는 * networks * > * subnets * 에서 서브테넌트에 대한 서브넷을 생성할 수 있습니다. 서브넷 정의에는 ONTAP에 구현되는 VLAN ID, CIDR 주소 범위 및 경로 사양이 포함됩니다. 서브넷은 테넌트 및 영역 내의 VLAN에 정렬됩니다. 존에 대해 동일한 VLAN으로 두 개의 서브넷을 생성할 수 없습니다.

.시작하기 전에
* 테넌트에 대해 VLAN 및 영역 구성이 이미 완료되어 있어야 합니다
* 생성할 서브넷의 요구 사항을 알고 있어야 합니다


.단계
. 필요한 테넌트를 선택합니다. 서브넷을 생성하는 하위 테넌트는 이 테넌트 아래에 있어야 합니다.
. networks * > * subnets * 를 클릭합니다. 서브테넌트에 대해 생성된 서브넷 목록은 * Subnets * 페이지에서 볼 수 있습니다.
. Create Subnet * 을 클릭합니다.
. 서브테넌트, 영역, 서브넷 이름, VLAN 및 서브넷 CIDR을 지정합니다. 배관 스팩과 태그를 추가할 수도 있습니다.
+

NOTE: 라우트 사양에서 * 대상 * 은 고유해야 하며, 지정된 VLAN의 일부여야 하며, 여러 라우트는 * Metric * 에 대해 같은 값을 가질 수 있습니다.

. Create * 를 클릭합니다.



NOTE: 서브넷은 편집하거나 삭제할 수 없습니다. 연관된 태그만 편집할 수 있습니다.
