---
sidebar: sidebar 
permalink: sewebiug_managing_gcp_cvs.html 
keywords: netapp, keystone, managing CVS for GCP, gcp, Google Cloud Volume, CVS, Cloud Volumes Service 
summary: Google Cloud Platform에서 Cloud Volume 서브스크립션 관리 
---
= Cloud Volumes Service for GCP 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
GCP(Cloud Volumes Service for Google Cloud Platform)에 대한 구독은 테넌트의 특정 하위 테넌트와 연결됩니다. 서브테넌트가 단일 Google Cloud 서비스에 가입되어 있습니다. 테넌트 및 하위 테넌트를 위해 클라우드 서비스(Google Cloud 인스턴스)를 생성 및 관리하고, 테넌트에 따라 Google Cloud에 스토리지를 프로비저닝할 수 있습니다. NetApp 서비스 엔진을 통해 Google Cloud 인스턴스를 관리하려면 테넌트 및 하위 테넌트의 Cloud Volumes Service 계정을 설정해야 합니다. GCP의 Cloud Volumes Service에 대한 자세한 내용은 을 참조하십시오 https://["Google Cloud용 Cloud Volumes Service에 대해 자세히 알아보십시오"].


NOTE: 테넌트 및 하위 테넌트의 Cloud Volumes Service 계정은 이미 GCP에 대해 구성되어 있어야 합니다. 서비스 계정 세부 정보는 지원 부서에 문의하십시오. Google Cloud Volumes를 관리하려면 고객 관리자 액세스 권한이 필요합니다.



== GCP에서 클라우드 서비스 관리

왼쪽 탐색 창의 * cloud services * 메뉴에서 Google Cloud에서 클라우드 서비스를 관리할 수 있습니다. 클라우드 서비스 페이지에는 선택한 테넌트의 모든 하위 테넌트에 대한 모든 클라우드 서비스가 표시됩니다. 이 페이지에서 클라우드 서비스를 확인, 수정 및 삭제할 수 있습니다. 다음 단계에 따라 새 서비스를 추가할 수도 있습니다.

.시작하기 전에
다음을 확인해야 합니다.

* 서브테넌트가 Google Cloud 서비스에 가입되어 있습니다.
* 가입자의 서비스 계정에 대한 JSON 파일이 있으며 Google Cloud 인스턴스와 연결된 GCP 프로젝트 번호를 알고 있습니다.
* 귀사의 지원 팀이 BlueXP에서 GCP용 Cloud Volumes Service를 이미 구성했는지 확인합니다. 자세한 내용은 을 참조하십시오 https://["Google Cloud용 Cloud Volumes Service를 설정합니다"].


.단계
. 메뉴에서 * 클라우드 서비스 * 를 선택합니다.
. 생성 * 을 클릭한 다음 * Google Cloud * 를 클릭합니다.
. Google Cloud용 클라우드 서비스 생성 페이지에서 서비스를 생성할 서브테넌트를 선택하고 이름 및 GCP 프로젝트 번호를 추가합니다.
. Google Cloud Credentials 섹션에서 서비스 계정의 자격 증명으로 JSON 파일을 업로드합니다.
. 필요한 경우 서비스에 태그를 추가합니다.
. Create * 를 클릭합니다. 서비스 상태가 생성되면 클라우드 서비스 페이지에서 '사용'으로 변경됩니다.




== GCP에서 볼륨 관리

GCP에서 클라우드 볼륨을 관리하기 전에 테넌트의 Cloud Volumes Service 계정을 생성하고 계정이 클라우드 볼륨에 가입되어야 합니다. 이러한 단계가 완료되었는지 확인하려면 지원 부서에 문의하십시오.

왼쪽 탐색 창의 * 파일 서비스 > GCP 볼륨 * 에서 GCP에 있는 서브테넌트의 볼륨을 관리할 수 있습니다. GCP Volumes 페이지에는 선택한 서브테넌트 및 해당 지역에 대해 GCP에서 생성한 기존 클라우드 볼륨이 나열됩니다. 이 페이지에서 기존 볼륨을 보고, 수정하고, 삭제할 수 있습니다. 다음 단계를 수행하여 새 클라우드 볼륨을 프로비저닝할 수도 있습니다.

.단계
. 메뉴에서 * 파일 서비스 > GCP Volumes * 를 선택합니다.
. Create * 를 클릭합니다. GCP 볼륨 생성 페이지가 표시됩니다.
. 볼륨을 생성할 서브테넌트를 선택합니다.
. 지역 및 네트워크를 선택합니다. 이 목록은 GCP에서 서브테넌트에 대한 Cloud Volumes Service 계정을 기반으로 필터링됩니다.
. 볼륨의 이름을 추가합니다.
. 적절한 서비스 수준을 선택합니다.
. 생성 토큰으로 볼륨의 파일 경로를 입력합니다.
. 볼륨 할당량을 바이트 단위로 할당합니다.
. 필요한 경우 볼륨에 대한 태그를 추가합니다.
. Create * 를 클릭합니다. 볼륨 상태가 생성되면 GCP Volumes 페이지에서 볼륨 상태가 'ucceed'로 변경됩니다.


다음 비디오에서 Cloud Volumes Service 및 NetApp 서비스 엔진을 통해 GCP에서 볼륨을 생성하는 방법을 알아보십시오.

video::Crq5a1zi1Vg[youtube,width=750,height=400]