---
sidebar: sidebar 
permalink: sewebiug_view_host_groups.html 
keywords: netapp, keystone, view, host, groups, 
summary: Keystone 보기 호스트 그룹 
---
= 호스트 그룹 작업
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
호스트 그룹은 디스크에 대한 액세스를 결정하기 위해 정의됩니다. 호스트 그룹에 할당된 이니시에이터 노드에 따라 해당 호스트 그룹의 액세스가 결정됩니다.



== 호스트 그룹을 봅니다

호스트 그룹 목록을 보려면 메뉴에서 * 블록 스토리지 > 호스트 그룹 * 을 선택합니다.

이 목록에는 정의된 호스트 그룹이 표시됩니다.

이 페이지에서 새 호스트 그룹을 생성하고, 호스트 그룹을 수정하고, 호스트 그룹을 삭제할 수 있습니다.



= 호스트 그룹을 생성합니다

호스트 그룹을 생성하는 방법에는 두 가지가 있습니다.

* 아래에 설명된 호스트 그룹 페이지에서 선택합니다.
* 새 디스크를 만들 때 사용합니다. 아직 초기화되지 않은 블록 저장소에 호스트 그룹을 만들어야 하는 경우 이 방법을 사용합니다. 자세한 내용은 을 참조하십시오 link:sewebiug_create_a_new_disk.html#create-a-new-disk["새 디스크를 만듭니다"].
+
빈 호스트 그룹을 생성하여 디스크에 자리 표시자로 매핑할 수 있습니다. 스토리지를 액세스하기 전에 빈 호스트 그룹을 업데이트하여 이니시에이터를 추가해야 합니다.



호스트 그룹을 생성하려면 다음이 필요합니다.

* 호스트 그룹을 생성할 서브테넌트, 지역 및 영역입니다.



NOTE: 서브테넌트/존 조합의 블록 저장소가 이전에 초기화되지 않은 경우 이 방법을 사용하여 호스트 그룹을 생성할 수 없습니다. 다른 방법은 을 따르는 것입니다 link:sewebiug_create_a_new_disk.html#create-a-new-disk["새 디스크를 만듭니다"] 프로세스의 일부로 블록 저장소를 초기화하고 호스트 그룹을 생성할 수 있는 프로세스입니다.

* 호스트 그룹의 이름입니다
* 호스트 그룹 프로토콜: iSCSI 또는 FCP
* 그룹에 추가할 이니시에이터 목록: FC 호스트 노드의 경우 WWPN, iSCSI 호스트 노드 이름의 경우 IQN
* 각 이니시에이터에 대한 별칭입니다. 별칭은 이니시에이터 서버 또는 서버의 개별 포트/인터페이스를 식별하기 위한 간단한 이름입니다. 예: 서버 4.


.단계
. link:sewebiug_view_host_groups.html#view-host-groups["호스트 그룹을 봅니다"] 목록.
. Create Host Group * 을 클릭합니다.
. 호스트 그룹 생성 페이지에서 다음을 수행합니다.
+
.. iSCSI 또는 FCP 프로토콜을 선택합니다.
.. 서브테넌트, 영역 및 영역과 호스트 그룹을 선택합니다.


. 호스트 그룹의 이름을 지정합니다.
. OS 유형: 디스크 운영 체제를 선택합니다.
. 그룹의 이니시에이터를 추가합니다. 각 이니시에이터에 대해 별칭과 이니시에이터를 지정합니다.
. 필요한 경우 태그 섹션의 호스트 그룹에 태그(키-값 쌍)를 추가합니다.
. Create * 를 클릭합니다. 그러면 호스트 그룹이 생성됩니다.


호스트 그룹을 생성한 후 디스크에 매핑할 수 있습니다.



== 호스트 그룹을 수정합니다

호스트 그룹을 수정하여 이니시에이터를 추가, 제거 또는 수정할 수 있습니다.

호스트 그룹을 수정하면 호스트 그룹에 매핑된 각 디스크에 대한 액세스가 수정됩니다.

이니시에이터의 별칭을 수정할 수 없습니다. 별칭을 변경하려면 그룹에서 이니시에이터를 삭제한 다음 다시 생성합니다.

.단계
. 를 봅니다 link:sewebiug_view_host_groups.html#view-host-groups["호스트 그룹"] 목록.
. 목록에서 호스트 그룹을 찾고 해당 호스트 그룹에 대한 편집 아이콘을 클릭합니다.
+
기존 이니시에이터를 수정하려면 목록에서 이니시에이터를 찾아 이니시에이터 값을 편집하고 * Update * 를 클릭합니다.

+
이니시에이터를 추가하려면

+
.. Add Initiator * 를 클릭합니다.
.. 별칭 및 이니시에이터를 지정합니다.
.. Create * 를 클릭합니다.
+
호스트 그룹에서 이니시에이터를 제거하려면 목록에서 이니시에이터를 찾아 삭제 아이콘을 클릭합니다.



. 완료 * 를 클릭합니다.




== 호스트 그룹을 삭제합니다

호스트 그룹에 매핑된 디스크가 없는 경우 호스트 그룹을 삭제할 수 있습니다.

.단계
. 를 봅니다 link:sewebiug_view_host_groups.html#view-host-groups["호스트 그룹"] 목록.
. 목록에서 호스트 그룹을 찾고 해당 호스트 그룹에 대한 삭제 아이콘을 클릭합니다.
. 삭제 확인 대화 상자에서 호스트 그룹 이름을 입력하여 호스트 그룹을 삭제할 것인지 확인합니다.
. 확인 * 을 클릭합니다.

