---
sidebar: sidebar 
permalink: sewebiug_alerts.html 
keywords: netapp, keystone, alert, create, custom alert 
summary: 알림을 생성하고 관리합니다 
---
= 알림을 생성하고 관리합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알림은 자동으로 트리거되거나 사용자 환경 내의 중요 이벤트에 대한 정보를 공유하기 위해 수동으로 생성되는 메시지입니다.

스토리지를 프로비저닝할 때 다음과 같은 경우에 자동 알림이 트리거됩니다.

* 새 디스크 또는 파일 공유에서는 구독이 버스트 모드로 푸시됩니다
* 새 디스크 또는 파일 공유가 새 구독에 프로비저닝됩니다
* 서브스크립션 내에서 사용된 용량이 임계값 용량을 초과했거나 커밋된 용량에 근접했습니다


Alerts * 화면을 사용하면 사용자 환경에서 시스템에서 생성하고 사용자가 생성한 경고를 볼 수 있습니다.

사용자 지정 알림을 만들어 다른 사용자에게 표시할 수도 있습니다. 필요에 따라 자신과 자신의 테넌시에 있는 다른 사용자에 대한 알림을 보고 해제할 수 있습니다.



== 멀티테넌트 환경에 경고를 생성합니다

파트너 관리자는 사용자 환경의 단일 테넌트 또는 모든 테넌트에 수동으로 알림을 생성하고 보낼 수 있습니다.


NOTE: 사용자가 만든 알림을 해제할 수 있습니다. 그러나 아직 보지 않은 테넌트에서만 해제됩니다.

.단계
. 메뉴에서 * administration * > * Alerts * 를 선택합니다.
. Create alert * 를 클릭합니다.
. 알림 생성 * 화면에서 알림을 보낼 상태 및 테넌트를 선택하고 메시지를 추가합니다.
+

NOTE: 환경에 있는 모든 테넌트에 알림을 보내려면 "모두"를 선택합니다.

. Create * 를 클릭합니다. 새 경고가 생성됩니다.




== 테넌시에 알림을 생성합니다

테넌트 관리자는 사용자 환경의 모든 사용자에게 알림을 수동으로 생성하고 보낼 수 있습니다.


NOTE: 사용자가 만든 알림을 해제할 수 있습니다. 그러나 아직 보지 않은 사용자에게만 해제됩니다.

.단계
. 메뉴에서 * administration * > * Alerts * 를 선택합니다.
. Create alert * 를 클릭합니다.
. Create alert * (경고 생성 *) 화면에서 상태를 선택하고 메시지를 추가합니다.
. Create * 를 클릭합니다. 새 경고가 생성됩니다.

