---
sidebar: sidebar 
permalink: sewebiug_modify_file_server.html 
keywords: netapp, keystone, modify, file, server, 
summary: 파일 서버를 수정합니다 
---
= 파일 서버를 수정합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
기존 서버를 다음과 같이 변경할 수 있습니다.

. 서버 이름을 변경합니다
. 서버를 CIFS로 설정하고 Active Directory 사용자 이름 및 암호, Active Directory 도메인, DNS 서버, 서버 이름 및 Active Directory 조직 구성 단위를 지정합니다(선택 사항). Active Directory 자격 증명은 컴퓨터를 Active Directory 도메인에 연결할 수 있는 권한이 있는 사용자에 대한 자격 증명이어야 합니다.
. 서버를 복제할 영역 또는 영역을 지정하여 비동기식 재해 복구 DP를 설정합니다.



NOTE: 비동기식 재해 복구가 이미 설정되어 있으면 해제할 수 없습니다. 자세한 내용은 을 참조하십시오 link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery["재해 복구"].

.단계
. 를 봅니다 link:sewebiug_view_servers.html#view-servers["파일 서버 목록"].
. 목록에서 서버를 찾고 해당 서버의 편집 아이콘을 클릭합니다. 목록의 항목 작업에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["목록 보기 작업"])를 클릭합니다.
. 필요에 따라 변경합니다. 을 참조하십시오 link:sewebiug_create_a_file_server.html["파일 서버를 생성합니다"] 필드 설명을 참조하십시오.
. 완료 * 를 클릭합니다. 이렇게 하면 서버를 수정할 작업이 생성됩니다.


수정 서버가 비동기 작업으로 실행됩니다. 다음을 수행할 수 있습니다.

* 작업 목록에서 작업의 상태를 확인합니다. 작업 추적에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["여기"].
* 작업이 완료된 후 Servers(서버) 목록에서 서버의 상태를 확인합니다.

