---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: 백업에서 백업 또는 복구를 생성, 수정 및 삭제합니다 
---
= 파일 공유 및 디스크를 백업합니다
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
운영 파일 공유 및 디스크의 여러 복제본을 원격으로 유지 관리하기 위해 사용자 환경에서 생성된 볼륨(파일 공유 및 디스크)의 스냅샷(백업 또는 복구 지점)을 보고 관리할 수 있습니다.

서로 다른 영역의 복제된 파일 공유 및 디스크는 각 클러스터의 전용 백업 스토리지 VM(SVM이라고도 함)에 저장됩니다. 서로 다른 영역에 있는 두 개의 개별 ONTAP 클러스터 간에 백업을 수행할 수 있습니다. NetApp Service Engine에서 지원하는 표준 백업 정책은 다음과 같습니다.

* 애드혹
* 매일
* 매주
* 매월


볼륨이 NetApp Service Engine에서 지원하는 표준 백업 정책을 따르지 않는 경우 다음을 수행할 수 있습니다 link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["서비스 요청을 제출하십시오"] 문제 해결을 위한 * 비표준 볼륨 * 범주.


NOTE: 임시(예약되지 않은) 백업은 언제든지 GUI를 통해 수동으로 또는 API를 사용하여 수행할 수 있습니다.

백업 * 페이지에서 파일 공유 및 디스크에 대해 생성된 스냅샷 목록을 볼 수 있습니다. 선택한 테넌트를 기반으로 백업이 표시됩니다.



== 백업 객체를 생성합니다

백업 정책을 정의할 때 볼륨에 대한 스냅샷을 생성할 수 있습니다 link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html["파일 공유를 생성합니다"] 또는 link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_disk.html["디스크를 만듭니다"].

.단계
. 백업 정책 * 을 활성화합니다.
. 백업 존 및 임시, 일별, 주별 및/또는 월별 기준으로 수행할 백업 수를 지정합니다.
. Create * 를 클릭합니다.



NOTE: 기존 파일 공유 또는 디스크에 대한 백업 정책을 편집하여 백업을 생성하거나 예약할 수도 있습니다.



== 백업 객체를 수정합니다

파일 공유 또는 디스크의 선택된 백업 객체에 대해 백업을 비활성화하거나 백업 객체를 소스에서 분리하여 분리된 백업으로 만들 수 있습니다. 이 작업으로 소스의 SnapMirror 관계가 끊어집니다. 또한 임시, 일별, 주별 및/또는 월별 기준으로 수행할 백업 수를 수정할 수 있습니다.

.단계
. 목록에서 백업을 찾고 해당 개체의 행 끝에 있는 편집 아이콘을 클릭합니다.
. 필요에 따라 백업 소스와 각 백업 유형의 수를 변경합니다. 백업 소스를 * 없음(분리됨) * 으로 변경하여 소스 볼륨과 SnapMirror 관계를 분리할 수 있습니다. 소스 볼륨이 삭제되더라도 백업은 복구를 위해 분리된 백업으로 유지됩니다. 백업 객체의 상태가 변경되고 소스 볼륨의 상태(분리된 볼륨 또는 삭제된 볼륨)가 동일한 목록의 소스 볼륨 이름에 추가됩니다. 개체 상태에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["여기"]
. 완료 * 를 클릭합니다. 스냅샷이 수정됩니다. 원본과 SnapMirror 관계를 끊어진 경우, 즉 백업 개체를 분리된 경우 * Backups * 탭의 소스 이름이 "삭제됨"으로 나타납니다.



NOTE: 볼륨에 대한 * 백업 정책 * 을 비활성화하여 소스 볼륨과의 SnapMirror 관계를 분리할 수도 있습니다.



== 백업 객체를 삭제합니다

사용하지 않는 백업 볼륨을 삭제하여 저장 공간을 늘리십시오.

.단계
. 목록에서 백업을 찾고 해당 개체의 행 끝에 있는 삭제 아이콘을 클릭합니다.
. 삭제 확인 * 대화 상자에서 백업 이름(소스 볼륨 이름)을 입력하여 백업 객체를 삭제할 것인지 확인합니다.
. 확인 * 을 클릭합니다.



NOTE: 백업이 삭제되면 백업의 모든 복구 지점이 삭제됩니다. 또한 기본 파일 공유 또는 디스크를 삭제하더라도 백업은 모든 복구 지점이 있는 분리된 백업으로 보존되어 복원할 수 있습니다. 삭제된 소스의 백업 볼륨 및 복구 지점을 삭제하려면 * Backups * 탭에서 백업 객체를 명시적으로 삭제해야 합니다.



== 백업 복원

가능합니다 link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html["서비스 요청을 제출하십시오"] 특정 복구 지점에서 파일 공유 또는 디스크를 복원합니다.

.단계
. 왼쪽 탐색 창에서 * 지원 * 을 선택하고 * 서비스 요청 * 을 선택합니다.
. 새 서비스 요청 * 을 클릭합니다.
. 서비스 요청의 범주로 백업 복원 * 을 선택합니다.
. 다른 세부 정보를 지정하고 계속 진행합니다.

