---
sidebar: sidebar 
permalink: sewebiug_partner_service_provider.html 
keywords: netapp, service, engine, web, portal, partner, service provider 
summary: NetApp 서비스 엔진 파트너, 서비스 공급자 직무 
---
= 서비스 공급자 및 고객의 역할 및 운영
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
서비스 공급자 또는 파트너(같은 뜻으로 혼용됨) 또는 고객 또는 테넌트(같은 의미로 사용됨) 관리자의 역할에 따라 NetApp Service Engine 웹 포털의 뷰 및 기능이 결정됩니다.



== 서비스 공급자 관리자로 수행할 수 있는 활동입니다

멀티 테넌트(multi-tenant) 환경의 서비스 공급자 관리자로서 NetApp Service Engine 웹 UI를 통해 고객이 직접 가입하여 프로비저닝, 보고, 청구 및 관리 기능을 수행할 수 있습니다. 다음 기능을 수행할 수 있습니다.

* Flex Subscription 서비스의 일부로 서비스 및 프로비저닝된 스토리지를 확인합니다.
+

NOTE: 즉, 고객은 NetApp에서 구매한 용량(초과 할당)보다 더 많은 용량을 고객에게 판매할 수 있습니다. 테넌트 구독은 현재 Flex Subscription 기간 이상으로 연장할 수 있지만 구독 생성 시 대시보드/보고서에 경고가 표시됩니다.

* 영역, 영역, 영역, 영역, 영역, 테넌트, 하위 테넌트 및 사용자
* Flex Subscription 서비스 내에서 여러 테넌트를 관리 및 호스팅: 테넌트 서브스크립션을 생성 및 관리하고 고유한 Flex Subscription 세부 정보를 확인합니다.
+

NOTE: 해당 존 및 Keystone Flex 구독에 따라 테넌트 구독을 생성할 수 있습니다. 이 서비스는 Flex Subscription의 서비스 용량에 따라 생성됩니다.

* 테넌트의 각 스토리지 유형 프로비저닝에 대한 네트워크 요구사항을 알고 있으므로 파일 서버 또는 블록 저장소를 생성하고 블록, 파일 및 오브젝트 스토리지를 초기화합니다.
* 테넌트의 서브넷을 생성하고 관리할 수도 있습니다.
* Flex Subscription의 일부로 생성된 파일 공유, 디스크 및 버킷을 볼 수 있습니다. 또한 오브젝트 스토리지 그룹 및 사용자를 생성하고 관리합니다.
* 각 청구 및 평가 시스템에서 사용하기 위해 NetApp Keystone Flex Subscription 및 테넌트 구독, 모든 테넌트의 사용 현황에 대한 보고서를 생성할 수 있습니다.
* 모든 테넌트 및 고객에 대한 비용 청구 및 보고, 구독 또는 프로비저닝된 스토리지에 대해서만 표시됩니다.
* 고객이 자체(파트너/서비스 공급자의) 서비스 요청 툴(OpsRamp/GSSC와 통합됨) 내에서 제기한 서비스 요청을 보고 관리합니다.




== 고객/테넌트 관리자로 수행할 수 있는 활동

테넌트 관리자는 자신의 테넌시에 대한 구독 세부 정보를 보고 하위 테넌트에 대한 관리 작업을 수행할 수 있는 권한을 얻을 수 있습니다. 다음 작업을 수행할 수 있습니다.

* 테넌트 구독 서비스의 일부로 서비스 및 프로비저닝된 스토리지를 봅니다.
* 테넌트 구독 서비스 내에서 여러 하위 테넌트 및 사용자를 관리하고 호스팅합니다.
* 영역, 영역, 테넌시, 서브넷을 봅니다.
* 파일 서버를 보고 파일 공유, 디스크 및 버킷을 생성합니다.
* 테넌트와 서브테넌트에 대한 보고서를 생성하여 테넌시와 서브테넌트에 대해 서비스 또는 프로비저닝된 스토리지에 대한 소비 데이터만 표시합니다.
* 서비스 공급자의 서비스 요청 도구 내에서 서비스 요청을 올리고 업데이트합니다.
+

NOTE: 추가 구독의 경우 서비스 요청 도구를 사용할 수 있습니다.


