---
sidebar: sidebar 
permalink: sewebiug_view_disks.html 
keywords: netapp, keystone, view, buckets, 
summary: Keystone 뷰 디스크 
---
= 디스크를 봅니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
디스크 목록에는 선택한 테넌트에 속한 디스크가 표시됩니다. 목록을 보려면 메뉴에서 * 블록 스토리지 > 디스크 * 를 선택합니다.

기존 환경에 이미 포함되어 있고 NetApp 서비스 엔진에 구성된 스토리지 VM에 속한 디스크는 이 화면에서도 볼 수 있으며, NetApp Keystone 유연한 구독(Flex Subscription) 서비스의 일부로 관리할 수 있습니다. NetApp 서비스 엔진 외부에서 프로비저닝된 디스크를 이 페이지에 주기적으로 가져와서 해당 상태 코드와 함께 나열합니다.

가져온 디스크가 NetApp Service Engine에서 사용할 수 있는 표준인 경우, 즉 디스크 작동에 필요한 모든 매개 변수를 사용할 수 있으면 해당 디스크를 "Operational" 상태로 가져와서 NetApp Service Engine을 통해 직접 관리할 수 있습니다. 그러나 일부 디스크는 NetApp 서비스 엔진의 기존 디스크와 동일한 표준에 있지 않을 수 있습니다. 가져오기 후 가져온 디스크 또는 Non-Standard 상태로 분류된다. 디스크 상태 및 작동 단계에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["개체 상태"]

디스크 목록에서 간단한 정보를 봅니다. 목록의 기능을 사용하는 방법에 대한 자세한 내용은 을 참조하십시오 link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["목록 보기 작업"].

* 디스크 이름입니다
* 디스크의 경로입니다
* 디스크 크기입니다
* 프로토콜
* 디스크가 속해 있는 서브테넌트입니다
* 디스크가 있는 영역입니다
* 작동 상태입니다

